// AUTO-GENERATED by scripts/generate_batch_fallbacks.py
// Do not edit by hand.

use crate::{
    calc_result::CalcResult,
    expressions::parser::Node,
    expressions::token::Error,
    expressions::types::CellReferenceIndex,
    model::Model,
};

const NORMALIZED_UNIMPLEMENTED_FUNCTIONS: [&str; 184] = [
    "ACCRINT",
    "ACCRINTM",
    "ADDRESS",
    "AGGREGATE",
    "AMORDEGRC",
    "AMORLINC",
    "ARRAYCONSTRAIN",
    "ASC",
    "AVERAGEWEIGHTED",
    "BAHTTEXT",
    "BYCOL",
    "BYROW",
    "CALL",
    "CHAR",
    "CHOOSECOLS",
    "CHOOSEROWS",
    "CLEAN",
    "CODE",
    "COPILOT",
    "COUNTUNIQUE",
    "COUPDAYBS",
    "COUPDAYS",
    "COUPDAYSNC",
    "COUPNCD",
    "COUPNUM",
    "COUPPCD",
    "CRITBINOM",
    "CUBEKPIMEMBER",
    "CUBEMEMBER",
    "CUBEMEMBERPROPERTY",
    "CUBERANKEDMEMBER",
    "CUBESET",
    "CUBESETCOUNT",
    "CUBEVALUE",
    "DBCS",
    "DETECTLANGUAGE",
    "DISC",
    "DIVIDE",
    "DOLLAR",
    "DROP",
    "DURATION",
    "ENCODEURL",
    "EPOCHTODATE",
    "EQ",
    "EUROCONVERT",
    "EXPAND",
    "FILTER",
    "FILTERXML",
    "FINDB",
    "FIXED",
    "FLATTEN",
    "FORECAST",
    "FORECASTETS",
    "FORECASTETSCONFINT",
    "FORECASTETSSEASONALITY",
    "FORECASTETSSTAT",
    "FORECASTLINEAR",
    "FREQUENCY",
    "FVSCHEDULE",
    "GETPIVOTDATA",
    "GOOGLEFINANCE",
    "GOOGLETRANSLATE",
    "GROUPBY",
    "GROWTH",
    "GT",
    "GTE",
    "HSTACK",
    "HYPERLINK",
    "IMAGE",
    "IMCOTH",
    "IMLOG",
    "IMPORTDATA",
    "IMPORTFEED",
    "IMPORTHTML",
    "IMPORTRANGE",
    "IMPORTXML",
    "IMTANH",
    "INTRATE",
    "ISBETWEEN",
    "ISDATE",
    "ISEMAIL",
    "ISOMITTED",
    "ISURL",
    "JIS",
    "JOIN",
    "LAMBDA",
    "LEFTB",
    "LENB",
    "LET",
    "LINEST",
    "LOGEST",
    "LT",
    "LTE",
    "MAKEARRAY",
    "MAP",
    "MARGINOFERROR",
    "MDETERM",
    "MDURATION",
    "MIDB",
    "MINUS",
    "MINVERSE",
    "MMULT",
    "MODE",
    "MODEMULT",
    "MODESNGL",
    "MULTINOMIAL",
    "MULTIPLY",
    "MUNIT",
    "NE",
    "NUMBERVALUE",
    "ODDFPRICE",
    "ODDFYIELD",
    "ODDLPRICE",
    "ODDLYIELD",
    "PERCENTILE",
    "PERCENTILEEXC",
    "PERCENTILEINC",
    "PERCENTRANK",
    "PERCENTRANKEXC",
    "PERCENTRANKINC",
    "PERMUT",
    "PERMUTATIONA",
    "PHONETIC",
    "PIVOTBY",
    "POW",
    "PRICE",
    "PRICEDISC",
    "PRICEMAT",
    "PROB",
    "PROPER",
    "QUARTILE",
    "QUARTILEEXC",
    "QUARTILEINC",
    "QUERY",
    "RANDARRAY",
    "RANK",
    "RECEIVED",
    "REDUCE",
    "REGEXEXTRACT",
    "REGEXMATCH",
    "REGEXREPLACE",
    "REGISTERID",
    "REPLACE",
    "REPLACEB",
    "RIGHTB",
    "RTD",
    "SCAN",
    "SEARCHB",
    "SEQUENCE",
    "SERIESSUM",
    "SORT",
    "SORTBY",
    "SORTN",
    "SPARKLINE",
    "SPLIT",
    "STOCKHISTORY",
    "SUMPRODUCT",
    "TAKE",
    "TEXTSPLIT",
    "TOCOL",
    "TOROW",
    "TODATE",
    "TODOLLARS",
    "TOPERCENT",
    "TOPURENUMBER",
    "TOTEXT",
    "TRANSPOSE",
    "TREND",
    "TRIMMEAN",
    "TRIMRANGE",
    "UMINUS",
    "UNARYPERCENT",
    "UNICHAR",
    "UNIQUE",
    "UPLUS",
    "VDB",
    "VSTACK",
    "WEBSERVICE",
    "WRAPCOLS",
    "WRAPROWS",
    "XMATCH",
    "YIELD",
    "YIELDDISC",
    "YIELDMAT",
];

pub(crate) fn normalize_function_name_for_fallbacks(name: &str) -> String {
    name.trim()
        .trim_start_matches("_xlfn.")
        .replace('.', "")
        .replace('_', "")
        .to_ascii_uppercase()
}

pub(crate) fn is_unsupported_function(name: &str) -> bool {
    let normalized = normalize_function_name_for_fallbacks(name);
    NORMALIZED_UNIMPLEMENTED_FUNCTIONS
        .iter()
        .any(|candidate| normalized == *candidate)
}

pub(crate) fn evaluate_batch_fallback(
    model: &mut Model,
    name: &str,
    args: &[Node],
    cell: CellReferenceIndex,
) -> Option<CalcResult> {
    match normalize_function_name_for_fallbacks(name).as_str() {
        "ADD" => {
            if args.len() < 2 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                Some(model.fn_sum(args, cell))
            }
        }
        "AREAS" => {
            if args.len() < 1 || args.len() > 1 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                match model.evaluate_node_in_context(&args[0], cell) {
                    CalcResult::Range { .. } | CalcResult::Array(_) => {
                        Some(CalcResult::Number(1.0))
                    }
                    CalcResult::Error { .. } => Some(CalcResult::new_error(
                        Error::NIMPL,
                        cell,
                        "AREAS requires a valid reference in this version".to_string(),
                    )),
                    _ => Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "AREAS expects a reference".to_string(),
                    )),
                }
            }
        }
        "ARRAYFORMULA" => {
            if args.len() < 1 || args.len() > 1 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                Some(model.evaluate_node_in_context(&args[0], cell))
            }
        }
        "BETAINVN" => Some(model.fn_beta_inv(args, cell)),
        _ => None,
    }
}
