// AUTO-GENERATED by scripts/generate_batch_fallbacks.py
// Do not edit by hand.

use std::collections::HashSet;

use chrono::{Datelike, DateTime, Timelike, Utc};

use crate::{
    calc_result::CalcResult,
    constants::EXCEL_DATE_BASE,
    expressions::parser::Node,
    expressions::parser::ArrayNode,
    expressions::token::Error,
    expressions::types::CellReferenceIndex,
    formatter::format::format_number,
    expressions::utils::number_to_column,
    functions::util::compare_values,
    cast::NumberOrArray,
    model::Model,
};

const NORMALIZED_UNIMPLEMENTED_FUNCTIONS: [&str; 0] = [
];

pub(crate) fn normalize_function_name_for_fallbacks(name: &str) -> String {
    name.trim()
        .trim_start_matches("_xlfn.")
        .replace('.', "")
        .replace('_', "")
        .to_ascii_uppercase()
}

pub(crate) fn is_unsupported_function(name: &str) -> bool {
    let normalized = normalize_function_name_for_fallbacks(name);
    NORMALIZED_UNIMPLEMENTED_FUNCTIONS
        .iter()
        .any(|candidate| normalized == *candidate)
}

pub(crate) fn evaluate_batch_fallback(
    model: &mut Model,
    name: &str,
    args: &[Node],
    cell: CellReferenceIndex,
) -> Option<CalcResult> {
    match normalize_function_name_for_fallbacks(name).as_str() {
        "ACCRINT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ACCRINTM" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ADD" => {
            if args.len() < 2 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                Some(model.fn_sum(args, cell))
            }
        }
        "ADDRESS" => {
            let arg_count = args.len();
            if arg_count < 2 || arg_count > 5 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let row = match model.get_number_no_bools(&args[0], cell) {
                Ok(f) => f.trunc() as i32,
                Err(e) => return Some(e),
            };
            let col = match model.get_number_no_bools(&args[1], cell) {
                Ok(f) => f.trunc() as i32,
                Err(e) => return Some(e),
            };
            if row <= 0 || col <= 0 {
                return Some(CalcResult::new_error(
                    Error::VALUE,
                    cell,
                    "Row and column must be positive".to_string(),
                ));
            }
            let abs_num = if arg_count >= 3 {
                match model.get_number_no_bools(&args[2], cell) {
                    Ok(f) => f.trunc() as i32,
                    Err(e) => return Some(e),
                }
            } else {
                1
            };
            let use_a1 = if arg_count >= 4 {
                match model.get_boolean(&args[3], cell) {
                    Ok(b) => b,
                    Err(e) => return Some(e),
                }
            } else {
                true
            };
            if !use_a1 {
                return Some(CalcResult::new_error(
                    Error::NIMPL,
                    cell,
                    "R1C1 addressing not implemented".to_string(),
                ));
            }
            let column = match number_to_column(col) {
                Some(c) => c,
                None => {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Invalid column".to_string(),
                    ))
                }
            };
            let (col_prefix, row_prefix) = match abs_num {
                1 => ("$", "$"),
                2 => ("", "$"),
                3 => ("$", ""),
                4 => ("", ""),
                _ => {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Invalid abs_num".to_string(),
                    ))
                }
            };
            let mut address = format!("{col_prefix}{column}{row_prefix}{row}");
            if arg_count == 5 {
                let sheet_text = match model.get_string(&args[4], cell) {
                    Ok(s) => s,
                    Err(e) => return Some(e),
                };
                if !sheet_text.is_empty() {
                    address = format!("{sheet_text}!{address}");
                }
            }
            Some(CalcResult::String(address))
        }
        "AGGREGATE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "AMORDEGRC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "AMORLINC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "AREAS" => {
            if args.len() < 1 || args.len() > 1 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                match model.evaluate_node_in_context(&args[0], cell) {
                    CalcResult::Range { .. } | CalcResult::Array(_) => {
                        Some(CalcResult::Number(1.0))
                    }
                    CalcResult::Error { .. } => Some(CalcResult::new_error(
                        Error::NIMPL,
                        cell,
                        "AREAS requires a valid reference in this version".to_string(),
                    )),
                    _ => Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "AREAS expects a reference".to_string(),
                    )),
                }
            }
        }
        "ARRAYFORMULA" => {
            if args.len() < 1 || args.len() > 1 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                Some(model.evaluate_node_in_context(&args[0], cell))
            }
        }
        "ARRAYCONSTRAIN" => {
            if args.len() != 3 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let rows = match model.get_number_no_bools(&args[1], cell) {
                Ok(f) => f.trunc() as i32,
                Err(e) => return Some(e),
            };
            let cols = match model.get_number_no_bools(&args[2], cell) {
                Ok(f) => f.trunc() as i32,
                Err(e) => return Some(e),
            };
            if rows <= 0 || cols <= 0 {
                return Some(CalcResult::new_error(
                    Error::VALUE,
                    cell,
                    "Rows and columns must be positive".to_string(),
                ));
            }
            let array = match model.get_number_or_array(&args[0], cell) {
                Ok(NumberOrArray::Number(f)) => vec![vec![ArrayNode::Number(f)]],
                Ok(NumberOrArray::Array(a)) => a,
                Err(e) => return Some(e),
            };
            let row_limit = rows as usize;
            let col_limit = cols as usize;
            let mut out = Vec::new();
            for row in array.into_iter().take(row_limit) {
                let mut out_row = Vec::new();
                for value in row.into_iter().take(col_limit) {
                    out_row.push(value);
                }
                out.push(out_row);
            }
            Some(CalcResult::Array(out))
        }
        "ASC" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let text = match model.get_string(&args[0], cell) {
                Ok(s) => s,
                Err(e) => return Some(e),
            };
            let mut out = String::new();
            for ch in text.chars() {
                let code = ch as u32;
                if code == 0x3000 {
                    out.push(' ');
                } else if (0xFF01..=0xFF5E).contains(&code) {
                    let mapped = char::from_u32(code - 0xFEE0).unwrap_or(ch);
                    out.push(mapped);
                } else {
                    out.push(ch);
                }
            }
            Some(CalcResult::String(out))
        }
        "AVERAGEWEIGHTED" => {
            if args.len() < 2 || args.len() % 2 != 0 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let mut weighted_sum = 0.0;
            let mut total_weight = 0.0;
            let mut pair_idx = 0;
            while pair_idx < args.len() {
                let values = match model.get_number_or_array(&args[pair_idx], cell) {
                    Ok(NumberOrArray::Number(f)) => vec![Some(f)],
                    Ok(NumberOrArray::Array(a)) => match model.values_from_array(a) {
                        Ok(v) => v,
                        Err(e) => {
                            return Some(CalcResult::new_error(
                                e,
                                cell,
                                "Error in values array".to_string(),
                            ))
                        }
                    },
                    Err(e) => return Some(e),
                };
                let weights = match model.get_number_or_array(&args[pair_idx + 1], cell) {
                    Ok(NumberOrArray::Number(f)) => vec![Some(f)],
                    Ok(NumberOrArray::Array(a)) => match model.values_from_array(a) {
                        Ok(v) => v,
                        Err(e) => {
                            return Some(CalcResult::new_error(
                                e,
                                cell,
                                "Error in weights array".to_string(),
                            ))
                        }
                    },
                    Err(e) => return Some(e),
                };
                if values.len() != weights.len() {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Values and weights must have the same length".to_string(),
                    ));
                }
                for idx in 0..values.len() {
                    if let (Some(v), Some(w)) = (values[idx], weights[idx]) {
                        weighted_sum += v * w;
                        total_weight += w;
                    }
                }
                pair_idx += 2;
            }
            if total_weight == 0.0 {
                return Some(CalcResult::new_error(
                    Error::DIV,
                    cell,
                    "Total weight is zero".to_string(),
                ));
            }
            Some(CalcResult::Number(weighted_sum / total_weight))
        }
        "BAHTTEXT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "BETAINVN" => Some(model.fn_beta_inv(args, cell)),
        "BYCOL" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "BYROW" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CALL" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CHAR" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let code = match model.get_number_no_bools(&args[0], cell) {
                Ok(f) => f.trunc() as i64,
                Err(e) => return Some(e),
            };
            if code <= 0 || code > 0x10FFFF {
                return Some(CalcResult::new_error(
                    Error::VALUE,
                    cell,
                    "Invalid character code".to_string(),
                ));
            }
            let ch = match char::from_u32(code as u32) {
                Some(c) => c,
                None => {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Invalid character code".to_string(),
                    ))
                }
            };
            Some(CalcResult::String(ch.to_string()))
        }
        "CHOOSECOLS" => {
            if args.len() < 2 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let array = match model.get_number_or_array(&args[0], cell) {
                Ok(NumberOrArray::Number(f)) => vec![vec![ArrayNode::Number(f)]],
                Ok(NumberOrArray::Array(a)) => a,
                Err(e) => return Some(e),
            };
            if array.is_empty() {
                return Some(CalcResult::Array(array));
            }
            let row_len = array.len();
            let col_len = array[0].len();
            let mut indices: Vec<usize> = Vec::new();
            for idx_node in &args[1..] {
                let raw = match model.get_number_no_bools(idx_node, cell) {
                    Ok(f) => f.trunc() as i32,
                    Err(e) => return Some(e),
                };
                if raw == 0 {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Index cannot be zero".to_string(),
                    ));
                }
                let resolved = if raw > 0 {
                    (raw - 1) as i32
                } else {
                    col_len as i32 + raw
                };
                if resolved < 0 || resolved >= col_len as i32 {
                    return Some(CalcResult::new_error(
                        Error::REF,
                        cell,
                        "Column index out of range".to_string(),
                    ));
                }
                indices.push(resolved as usize);
            }
            let mut out = Vec::new();
            for row in array.into_iter().take(row_len) {
                let mut out_row = Vec::new();
                for idx in &indices {
                    if *idx >= row.len() {
                        return Some(CalcResult::new_error(
                            Error::REF,
                            cell,
                            "Column index out of range".to_string(),
                        ));
                    }
                    out_row.push(row[*idx].clone());
                }
                out.push(out_row);
            }
            Some(CalcResult::Array(out))
        }
        "CHOOSEROWS" => {
            if args.len() < 2 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let array = match model.get_number_or_array(&args[0], cell) {
                Ok(NumberOrArray::Number(f)) => vec![vec![ArrayNode::Number(f)]],
                Ok(NumberOrArray::Array(a)) => a,
                Err(e) => return Some(e),
            };
            if array.is_empty() {
                return Some(CalcResult::Array(array));
            }
            let row_len = array.len();
            let mut indices: Vec<usize> = Vec::new();
            for idx_node in &args[1..] {
                let raw = match model.get_number_no_bools(idx_node, cell) {
                    Ok(f) => f.trunc() as i32,
                    Err(e) => return Some(e),
                };
                if raw == 0 {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Index cannot be zero".to_string(),
                    ));
                }
                let resolved = if raw > 0 {
                    (raw - 1) as i32
                } else {
                    row_len as i32 + raw
                };
                if resolved < 0 || resolved >= row_len as i32 {
                    return Some(CalcResult::new_error(
                        Error::REF,
                        cell,
                        "Row index out of range".to_string(),
                    ));
                }
                indices.push(resolved as usize);
            }
            let mut out = Vec::new();
            for idx in indices {
                if idx >= array.len() {
                    return Some(CalcResult::new_error(
                        Error::REF,
                        cell,
                        "Row index out of range".to_string(),
                    ));
                }
                out.push(array[idx].clone());
            }
            Some(CalcResult::Array(out))
        }
        "CLEAN" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let text = match model.get_string(&args[0], cell) {
                Ok(s) => s,
                Err(e) => return Some(e),
            };
            let filtered: String = text.chars().filter(|c| (*c as u32) > 0x1F).collect();
            Some(CalcResult::String(filtered))
        }
        "CODE" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let text = match model.get_string(&args[0], cell) {
                Ok(s) => s,
                Err(e) => return Some(e),
            };
            let mut chars = text.chars();
            let ch = match chars.next() {
                Some(c) => c,
                None => {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Empty string".to_string(),
                    ))
                }
            };
            Some(CalcResult::Number(ch as u32 as f64))
        }
        "COPILOT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "COUNTUNIQUE" => {
            if args.is_empty() {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let mut seen: HashSet<String> = HashSet::new();
            for arg in args {
                let value = model.evaluate_node_in_context(arg, cell);
                match value {
                    CalcResult::Number(f) => {
                        seen.insert(format!("n:{f}"));
                    }
                    CalcResult::String(s) => {
                        seen.insert(format!("s:{s}"));
                    }
                    CalcResult::Boolean(b) => {
                        seen.insert(format!("b:{b}"));
                    }
                    CalcResult::EmptyCell | CalcResult::EmptyArg => {}
                    CalcResult::Range { left, right } => {
                        if left.sheet != right.sheet {
                            return Some(CalcResult::new_error(
                                Error::ERROR,
                                cell,
                                "3D ranges are not allowed".to_string(),
                            ));
                        }
                        for row in left.row..=right.row {
                            for column in left.column..=right.column {
                                let cell_value = model.evaluate_cell(CellReferenceIndex {
                                    sheet: left.sheet,
                                    row,
                                    column,
                                });
                                match cell_value {
                                    CalcResult::Number(f) => {
                                        seen.insert(format!("n:{f}"));
                                    }
                                    CalcResult::String(s) => {
                                        seen.insert(format!("s:{s}"));
                                    }
                                    CalcResult::Boolean(b) => {
                                        seen.insert(format!("b:{b}"));
                                    }
                                    CalcResult::EmptyCell | CalcResult::EmptyArg => {}
                                    error @ CalcResult::Error { .. } => {
                                        return Some(error);
                                    }
                                    _ => {}
                                }
                            }
                        }
                    }
                    CalcResult::Array(array) => {
                        for row in array {
                            for item in row {
                                match item {
                                    ArrayNode::Number(f) => {
                                        seen.insert(format!("n:{f}"));
                                    }
                                    ArrayNode::String(s) => {
                                        seen.insert(format!("s:{s}"));
                                    }
                                    ArrayNode::Boolean(b) => {
                                        seen.insert(format!("b:{b}"));
                                    }
                                    ArrayNode::Error(error) => {
                                        return Some(CalcResult::new_error(
                                            error,
                                            cell,
                                            "Error in array".to_string(),
                                        ));
                                    }
                                }
                            }
                        }
                    }
                    error @ CalcResult::Error { .. } => {
                        return Some(error);
                    }
                }
            }
            Some(CalcResult::Number(seen.len() as f64))
        }
        "COUPDAYBS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "COUPDAYS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "COUPDAYSNC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "COUPNCD" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "COUPNUM" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "COUPPCD" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CRITBINOM" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CUBEKPIMEMBER" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CUBEMEMBER" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CUBEMEMBERPROPERTY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CUBERANKEDMEMBER" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CUBESET" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CUBESETCOUNT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "CUBEVALUE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "DBCS" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let text = match model.get_string(&args[0], cell) {
                Ok(s) => s,
                Err(e) => return Some(e),
            };
            let mut out = String::new();
            for ch in text.chars() {
                let code = ch as u32;
                if code == 0x20 {
                    out.push(char::from_u32(0x3000).unwrap());
                } else if (0x21..=0x7E).contains(&code) {
                    let mapped = char::from_u32(code + 0xFEE0).unwrap_or(ch);
                    out.push(mapped);
                } else {
                    out.push(ch);
                }
            }
            Some(CalcResult::String(out))
        }
        "DETECTLANGUAGE" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let text = match model.get_string(&args[0], cell) {
                Ok(s) => s,
                Err(e) => return Some(e),
            };
            let lang = if text.is_ascii() { "en" } else { "und" };
            Some(CalcResult::String(lang.to_string()))
        }
        "DISC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "DIVIDE" => {
            if args.len() != 2 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let numerator = match model.get_number_no_bools(&args[0], cell) {
                Ok(f) => f,
                Err(e) => return Some(e),
            };
            let denominator = match model.get_number_no_bools(&args[1], cell) {
                Ok(f) => f,
                Err(e) => return Some(e),
            };
            if denominator == 0.0 {
                return Some(CalcResult::new_error(
                    Error::DIV,
                    cell,
                    "Division by zero".to_string(),
                ));
            }
            Some(CalcResult::Number(numerator / denominator))
        }
        "DOLLAR" => {
            if args.is_empty() || args.len() > 2 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let value = match model.get_number_no_bools(&args[0], cell) {
                Ok(f) => f,
                Err(e) => return Some(e),
            };
            let decimals = if args.len() == 2 {
                match model.get_number_no_bools(&args[1], cell) {
                    Ok(f) => f.trunc() as i32,
                    Err(e) => return Some(e),
                }
            } else {
                2
            };
            let decimals = if decimals < 0 { 0 } else { decimals };
            let mut format_code = String::from("$#,##0");
            if decimals > 0 {
                format_code.push('.');
                format_code.push_str(&"0".repeat(decimals as usize));
            }
            let formatted = format_number(value, &format_code, model.locale);
            if formatted.error.is_some() {
                return Some(CalcResult::new_error(
                    Error::VALUE,
                    cell,
                    "Invalid format".to_string(),
                ));
            }
            Some(CalcResult::String(formatted.text))
        }
        "DROP" => {
            if args.len() < 2 || args.len() > 3 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let rows = match model.get_number_no_bools(&args[1], cell) {
                Ok(f) => f.trunc() as i32,
                Err(e) => return Some(e),
            };
            let cols = if args.len() == 3 {
                match model.get_number_no_bools(&args[2], cell) {
                    Ok(f) => f.trunc() as i32,
                    Err(e) => return Some(e),
                }
            } else {
                0
            };
            let array = match model.get_number_or_array(&args[0], cell) {
                Ok(NumberOrArray::Number(f)) => vec![vec![ArrayNode::Number(f)]],
                Ok(NumberOrArray::Array(a)) => a,
                Err(e) => return Some(e),
            };
            if array.is_empty() {
                return Some(CalcResult::Array(array));
            }
            let row_len = array.len();
            let col_len = array[0].len();
            let (row_start, row_end) = if rows >= 0 {
                let start = usize::min(rows as usize, row_len);
                (start, row_len)
            } else {
                let drop = usize::min(rows.unsigned_abs() as usize, row_len);
                (0, row_len.saturating_sub(drop))
            };
            let (col_start, col_end) = if cols >= 0 {
                let start = usize::min(cols as usize, col_len);
                (start, col_len)
            } else {
                let drop = usize::min(cols.unsigned_abs() as usize, col_len);
                (0, col_len.saturating_sub(drop))
            };
            let mut out = Vec::new();
            for row in array.into_iter().skip(row_start).take(row_end.saturating_sub(row_start)) {
                if row.is_empty() {
                    out.push(row);
                    continue;
                }
                let mut out_row = Vec::new();
                for value in row.into_iter().skip(col_start).take(col_end.saturating_sub(col_start)) {
                    out_row.push(value);
                }
                out.push(out_row);
            }
            Some(CalcResult::Array(out))
        }
        "DURATION" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ENCODEURL" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let text = match model.get_string(&args[0], cell) {
                Ok(s) => s,
                Err(e) => return Some(e),
            };
            let mut out = String::new();
            for byte in text.as_bytes() {
                let ch = *byte as char;
                let keep = (ch >= 'A' && ch <= 'Z')
                    || (ch >= 'a' && ch <= 'z')
                    || (ch >= '0' && ch <= '9')
                    || matches!(ch, '-' | '_' | '.' | '~');
                if keep {
                    out.push(ch);
                } else {
                    out.push_str(&format!("%{:02X}", *byte));
                }
            }
            Some(CalcResult::String(out))
        }
        "EPOCHTODATE" => {
            if args.len() != 1 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let seconds = match model.get_number_no_bools(&args[0], cell) {
                Ok(f) => f,
                Err(e) => return Some(e),
            };
            let secs = seconds.floor() as i64;
            let frac = seconds - secs as f64;
            let nanos = (frac.abs() * 1_000_000_000.0).round() as u32;
            let dt = match DateTime::<Utc>::from_timestamp(secs, nanos) {
                Some(d) => d.naive_utc(),
                None => {
                    return Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "Invalid epoch timestamp".to_string(),
                    ))
                }
            };
            let days_from_ce = dt.date().num_days_from_ce() as i64;
            let seconds_in_day = dt.time().num_seconds_from_midnight() as f64
                + (dt.time().nanosecond() as f64 / 1_000_000_000.0);
            let fraction = seconds_in_day / 86_400.0;
            let serial = (days_from_ce - EXCEL_DATE_BASE as i64) as f64 + fraction;
            Some(CalcResult::Number(serial))
        }
        "EQ" => {
            if args.len() != 2 {
                return Some(CalcResult::new_args_number_error(cell));
            }
            let left = model.evaluate_node_in_context(&args[0], cell);
            if left.is_error() {
                return Some(left);
            }
            let right = model.evaluate_node_in_context(&args[1], cell);
            if right.is_error() {
                return Some(right);
            }
            Some(CalcResult::Boolean(compare_values(&left, &right) == 0))
        }
        "EUROCONVERT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "EXPAND" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FILTER" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FILTERXML" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FINDB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FIXED" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FLATTEN" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FORECAST" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FORECASTETS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FORECASTETSCONFINT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FORECASTETSSEASONALITY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FORECASTETSSTAT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FORECASTLINEAR" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FREQUENCY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "FVSCHEDULE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "GETPIVOTDATA" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "GOOGLEFINANCE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "GOOGLETRANSLATE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "GROUPBY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "GROWTH" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "GT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "GTE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "HSTACK" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "HYPERLINK" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMAGE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMCOTH" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMLOG" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMPORTDATA" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMPORTFEED" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMPORTHTML" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMPORTRANGE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMPORTXML" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "IMTANH" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "INTRATE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ISBETWEEN" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ISDATE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ISEMAIL" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ISOMITTED" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ISURL" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "JIS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "JOIN" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LAMBDA" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LEFTB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LENB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LET" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LINEST" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LOGEST" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "LTE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MAKEARRAY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MAP" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MARGINOFERROR" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MDETERM" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MDURATION" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MIDB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MINUS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MINVERSE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MMULT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MODE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MODEMULT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MODESNGL" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MULTINOMIAL" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MULTIPLY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "MUNIT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "NE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "NUMBERVALUE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ODDFPRICE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ODDFYIELD" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ODDLPRICE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "ODDLYIELD" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERCENTILE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERCENTILEEXC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERCENTILEINC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERCENTRANK" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERCENTRANKEXC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERCENTRANKINC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERMUT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PERMUTATIONA" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PHONETIC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PIVOTBY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "POW" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PRICE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PRICEDISC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PRICEMAT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PROB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "PROPER" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "QUARTILE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "QUARTILEEXC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "QUARTILEINC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "QUERY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "RANDARRAY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "RANK" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "RECEIVED" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "REDUCE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "REGEXEXTRACT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "REGEXMATCH" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "REGEXREPLACE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "REGISTERID" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "REPLACE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "REPLACEB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "RIGHTB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "RTD" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SCAN" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SEARCHB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SEQUENCE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SERIESSUM" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SORT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SORTBY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SORTN" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SPARKLINE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SPLIT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "STOCKHISTORY" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "SUMPRODUCT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TAKE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TEXTSPLIT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TOCOL" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TOROW" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TODATE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TODOLLARS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TOPERCENT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TOPURENUMBER" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TOTEXT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TRANSPOSE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TREND" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TRIMMEAN" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "TRIMRANGE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "UMINUS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "UNARYPERCENT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "UNICHAR" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "UNIQUE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "UPLUS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "VDB" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "VSTACK" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "WEBSERVICE" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "WRAPCOLS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "WRAPROWS" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "XMATCH" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "YIELD" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "YIELDDISC" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        "YIELDMAT" => {
            Some(CalcResult::new_error(
                Error::NIMPL,
                cell,
                "Function not supported yet".to_string(),
            ))
        }
        _ => None,
    }
}
