// AUTO-GENERATED by scripts/generate_batch_fallbacks.py
// Do not edit by hand.

use crate::{
    calc_result::CalcResult,
    expressions::parser::Node,
    expressions::token::Error,
    expressions::types::CellReferenceIndex,
    model::Model,
};

const NORMALIZED_BATCH1_UNIMPLEMENTED_FUNCTIONS: [&str; 10] = [
    "ACCRINT",
    "ACCRINTM",
    "ADDRESS",
    "AGGREGATE",
    "AMORDEGRC",
    "AMORLINC",
    "ARRAYCONSTRAIN",
    "ASC",
    "AVERAGEWEIGHTED",
    "BAHTTEXT",
];

pub(crate) fn normalize_function_name_for_batch1(name: &str) -> String {
    name.trim()
        .trim_start_matches("_xlfn.")
        .replace('.', "")
        .replace('_', "")
        .to_ascii_uppercase()
}

pub(crate) fn is_batch1_unsupported_function(name: &str) -> bool {
    let normalized = normalize_function_name_for_batch1(name);
    NORMALIZED_BATCH1_UNIMPLEMENTED_FUNCTIONS
        .iter()
        .any(|candidate| normalized == *candidate)
}

pub(crate) fn evaluate_batch1_fallback(
    model: &mut Model,
    name: &str,
    args: &[Node],
    cell: CellReferenceIndex,
) -> Option<CalcResult> {
    match normalize_function_name_for_batch1(name).as_str() {
        "AREAS" => {
            if args.len() < 1 || args.len() > 1 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                match model.evaluate_node_in_context(&args[0], cell) {
                    CalcResult::Range { .. } | CalcResult::Array(_) => {
                        Some(CalcResult::Number(1.0))
                    }
                    CalcResult::Error { .. } => Some(CalcResult::new_error(
                        Error::NIMPL,
                        cell,
                        "AREAS requires a valid reference in this version".to_string(),
                    )),
                    _ => Some(CalcResult::new_error(
                        Error::VALUE,
                        cell,
                        "AREAS expects a reference".to_string(),
                    )),
                }
            }
        }
        "ARRAYFORMULA" => {
            if args.len() < 1 || args.len() > 1 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                Some(model.evaluate_node_in_context(&args[0], cell))
            }
        }
        "ADD" => {
            if args.len() < 2 {
                Some(CalcResult::new_args_number_error(cell))
            } else {
                Some(model.fn_sum(args, cell))
            }
        }
        "BETAINVN" => Some(model.fn_beta_inv(args, cell)),
        _ => None,
    }
}
