#!/usr/bin/env python3
import csv
import html
import json
import re
import sys
from pathlib import Path
from typing import Iterable, List, Set

import urllib.request

EXCEL_URL = "https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188"
SHEETS_URL = "https://support.google.com/docs/table/25273?hl=en"

ROOT = Path(__file__).resolve().parents[1]
LANG_PATH = ROOT / "base" / "src" / "language" / "language.json"
OUT_CSV = ROOT / "specs" / "matrices" / "function_matrix.csv"
OUT_MD = ROOT / "specs" / "matrices" / "function_matrix.md"


def fetch(url: str) -> str:
    print(f"Fetching {url}...")
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 (compatible; IronCalc-Compare/1.0)",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", errors="replace")


def normalize(name: str) -> str:
    name = name.strip()
    name = re.sub(r"\s+", " ", name)
    name = name.replace("\u00a0", " ")
    return name.upper()


def extract_excel_functions(html_text: str) -> Set[str]:
    print("Parsing Excel function list...")
    rows = re.findall(r"<tr[^>]*>(.*?)</tr>", html_text, flags=re.S | re.I)
    names: List[str] = []
    for row in rows:
        cells = re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", row, flags=re.S | re.I)
        if not cells:
            continue
        first = html.unescape(re.sub(r"<[^>]+>", "", cells[0]))
        first = first.strip()
        if not first:
            continue
        if "function name" in first.lower():
            continue
        first = re.sub(r"\([^)]*\)", "", first).strip()
        first = re.sub(r"\*+$", "", first).strip()
        first = normalize(first)
        if re.fullmatch(r"[A-Z0-9_.]+", first):
            names.append(first)
    return set(names)


def extract_sheets_functions(html_text: str) -> Set[str]:
    print("Parsing Google Sheets function list...")
    codes = re.findall(r"<code[^>]*>(.*?)</code>", html_text, flags=re.S | re.I)
    names: Set[str] = set()
    for code in codes:
        text = html.unescape(re.sub(r"<[^>]+>", "", code)).strip()
        m = re.match(r"([A-Za-z0-9_.]+)\s*\(", text)
        if not m:
            continue
        name = normalize(m.group(1))
        if re.fullmatch(r"[A-Z0-9_.]+", name):
            names.add(name)
    return names


def extract_ironcalc_functions() -> Set[str]:
    print("Loading IronCalc function list...")
    data = json.loads(LANG_PATH.read_text())
    funcs = data["en"]["functions"].values()
    return {normalize(f) for f in funcs}


def write_outputs(all_funcs: Iterable[str], ironcalc: Set[str], excel: Set[str], sheets: Set[str]) -> None:
    print("Writing outputs...")
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for fn in sorted(all_funcs):
        in_iron = "Y" if fn in ironcalc else "N"
        in_excel = "Y" if fn in excel else "N"
        in_sheets = "Y" if fn in sheets else "N"
        if in_excel == "Y" and in_sheets == "Y":
            origin = "Excel+Sheets"
        elif in_excel == "Y":
            origin = "Excel-only"
        elif in_sheets == "Y":
            origin = "Sheets-only"
        else:
            origin = "IronCalc-only"
        rows.append([fn, in_iron, in_excel, in_sheets, origin])

    with OUT_CSV.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Function", "IronCalc", "Excel", "GoogleSheets", "Origin"])
        writer.writerows(rows)

    total = len(set(all_funcs))
    iron_total = len(ironcalc)
    excel_total = len(excel)
    sheets_total = len(sheets)
    iron_in_excel = len(ironcalc & excel)
    iron_in_sheets = len(ironcalc & sheets)
    excel_missing = len(excel - ironcalc)
    sheets_missing = len(sheets - ironcalc)

    OUT_MD.write_text(
        "\n".join(
            [
                "# Function Coverage Matrix",
                "",
                "Generated by `scripts/compare_functions.py`.",
                "",
                "## Summary",
                f"- Total unique functions (union): {total}",
                f"- IronCalc functions: {iron_total}",
                f"- Excel functions: {excel_total}",
                f"- Google Sheets functions: {sheets_total}",
                f"- IronCalc in Excel: {iron_in_excel}",
                f"- IronCalc in Sheets: {iron_in_sheets}",
                f"- Excel functions missing in IronCalc: {excel_missing}",
                f"- Sheets functions missing in IronCalc: {sheets_missing}",
                "",
                "## Full Matrix",
                "",
                "See `specs/function_matrix.csv` for the complete list.",
                "",
            ]
        )
    )


def main() -> int:
    if not LANG_PATH.exists():
        print(f"Missing IronCalc language file: {LANG_PATH}", file=sys.stderr)
        return 1

    try:
        excel_html = fetch(EXCEL_URL)
        sheets_html = fetch(SHEETS_URL)
    except Exception as exc:
        print(f"Fetch failed: {exc}", file=sys.stderr)
        return 2

    excel_funcs = extract_excel_functions(excel_html)
    sheets_funcs = extract_sheets_functions(sheets_html)
    iron_funcs = extract_ironcalc_functions()

    if not excel_funcs:
        print("No Excel functions found; parsing may have failed.", file=sys.stderr)
    if not sheets_funcs:
        print("No Sheets functions found; parsing may have failed.", file=sys.stderr)

    all_funcs = set().union(iron_funcs, excel_funcs, sheets_funcs)
    write_outputs(all_funcs, iron_funcs, excel_funcs, sheets_funcs)
    print(f"Wrote {OUT_CSV}")
    print(f"Wrote {OUT_MD}")
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
