#!/usr/bin/env python3
import argparse
import csv
from pathlib import Path
from typing import Dict, List


ROOT = Path(__file__).resolve().parents[1]
FALLBACKS_CSV = ROOT / "specs" / "pipelines" / "function_fallbacks.csv"
OUT_FALLBACKS_RS = ROOT / "base" / "src" / "batch_fallbacks.rs"
OUT_TEST_RS = ROOT / "base" / "src" / "test" / "test_fn_batch_fallbacks.rs"


def sanitize_test_name(name: str) -> str:
    out = []
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    return "".join(out).strip("_")


def escape_rust_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"")


def load_rows(batch: str) -> List[Dict[str, str]]:
    if not FALLBACKS_CSV.exists():
        raise SystemExit(f"Missing fallback table: {FALLBACKS_CSV}")
    rows: List[Dict[str, str]] = []
    with FALLBACKS_CSV.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if not row.get("batch_id"):
                continue
            if batch != "all" and int(row["batch_id"]) != int(batch):
                continue
            rows.append(row)
    if not rows:
        raise SystemExit(f"No fallback rows for batch {batch}")
    return rows


def gen_fallbacks_rs(rows: List[Dict[str, str]]) -> str:
    unimplemented = [
        r["function_name"] for r in rows if r.get("action") == "unimplemented"
    ]
    unimplemented_norm = [r.replace(".", "").replace("_", "").upper() for r in unimplemented]

    needs_array = any(
        (r.get("action") or "").strip() in ("array_constrain", "average_weighted")
        for r in rows
    )
    needs_array_node = any(
        (r.get("action") or "").strip() == "array_constrain" for r in rows
    )
    needs_number_to_column = any(
        (r.get("action") or "").strip() == "address_basic" for r in rows
    )
    needs_string = any((r.get("action") or "").strip() == "asc" for r in rows)

    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_batch_fallbacks.py")
    lines.append("// Do not edit by hand.")
    lines.append("")
    lines.append("use crate::{")
    lines.append("    calc_result::CalcResult,")
    lines.append("    expressions::parser::Node,")
    if needs_array_node:
        lines.append("    expressions::parser::ArrayNode,")
    lines.append("    expressions::token::Error,")
    lines.append("    expressions::types::CellReferenceIndex,")
    if needs_number_to_column:
        lines.append("    expressions::utils::number_to_column,")
    if needs_array:
        lines.append("    cast::NumberOrArray,")
    lines.append("    model::Model,")
    lines.append("};")
    lines.append("")
    lines.append(
        f"const NORMALIZED_UNIMPLEMENTED_FUNCTIONS: [&str; {len(unimplemented_norm)}] = ["
    )
    for name in unimplemented_norm:
        lines.append(f'    "{name}",')
    lines.append("];")
    lines.append("")
    lines.append("pub(crate) fn normalize_function_name_for_fallbacks(name: &str) -> String {")
    lines.append("    name.trim()")
    lines.append('        .trim_start_matches("_xlfn.")')
    lines.append('        .replace(\'.\', "")')
    lines.append('        .replace(\'_\', "")')
    lines.append("        .to_ascii_uppercase()")
    lines.append("}")
    lines.append("")
    lines.append("pub(crate) fn is_unsupported_function(name: &str) -> bool {")
    lines.append("    let normalized = normalize_function_name_for_fallbacks(name);")
    lines.append("    NORMALIZED_UNIMPLEMENTED_FUNCTIONS")
    lines.append("        .iter()")
    lines.append("        .any(|candidate| normalized == *candidate)")
    lines.append("}")
    lines.append("")
    lines.append("pub(crate) fn evaluate_batch_fallback(")
    lines.append("    model: &mut Model,")
    lines.append("    name: &str,")
    lines.append("    args: &[Node],")
    lines.append("    cell: CellReferenceIndex,")
    lines.append(") -> Option<CalcResult> {")
    lines.append("    match normalize_function_name_for_fallbacks(name).as_str() {")
    for row in rows:
        action = (row.get("action") or "").strip()
        name = row["function_name"]
        normalized = name.replace(".", "").replace("_", "").upper()
        if action in ("", "implemented", "unimplemented"):
            continue
        if action == "alias_sum":
            min_args = row.get("min_args", "").strip()
            if min_args:
                lines.append(f'        "{normalized}" => {{')
                lines.append(f"            if args.len() < {min_args} {{")
                lines.append("                Some(CalcResult::new_args_number_error(cell))")
                lines.append("            } else {")
                lines.append("                Some(model.fn_sum(args, cell))")
                lines.append("            }")
                lines.append("        }")
            else:
                lines.append(f'        "{normalized}" => Some(model.fn_sum(args, cell)),')
        elif action == "alias_beta_inv":
            lines.append(f'        "{normalized}" => Some(model.fn_beta_inv(args, cell)),')
        elif action == "passthrough":
            min_args = int(row.get("min_args", "1") or "1")
            max_args = int(row.get("max_args", "1") or "1")
            lines.append(f'        "{normalized}" => {{')
            lines.append(f"            if args.len() < {min_args} || args.len() > {max_args} {{")
            lines.append("                Some(CalcResult::new_args_number_error(cell))")
            lines.append("            } else {")
            lines.append("                Some(model.evaluate_node_in_context(&args[0], cell))")
            lines.append("            }")
            lines.append("        }")
        elif action == "areas_simple":
            min_args = int(row.get("min_args", "1") or "1")
            max_args = int(row.get("max_args", "1") or "1")
            lines.append(f'        "{normalized}" => {{')
            lines.append(f"            if args.len() < {min_args} || args.len() > {max_args} {{")
            lines.append("                Some(CalcResult::new_args_number_error(cell))")
            lines.append("            } else {")
            lines.append("                match model.evaluate_node_in_context(&args[0], cell) {")
            lines.append("                    CalcResult::Range { .. } | CalcResult::Array(_) => {")
            lines.append("                        Some(CalcResult::Number(1.0))")
            lines.append("                    }")
            lines.append("                    CalcResult::Error { .. } => Some(CalcResult::new_error(")
            lines.append("                        Error::NIMPL,")
            lines.append("                        cell,")
            lines.append('                        "AREAS requires a valid reference in this version".to_string(),')
            lines.append("                    )),")
            lines.append("                    _ => Some(CalcResult::new_error(")
            lines.append("                        Error::VALUE,")
            lines.append("                        cell,")
            lines.append('                        "AREAS expects a reference".to_string(),')
            lines.append("                    )),")
            lines.append("                }")
            lines.append("            }")
            lines.append("        }")
        elif action == "address_basic":
            lines.append(f'        "{normalized}" => {{')
            lines.append("            let arg_count = args.len();")
            lines.append("            if arg_count < 2 || arg_count > 5 {")
            lines.append("                return Some(CalcResult::new_args_number_error(cell));")
            lines.append("            }")
            lines.append("            let row = match model.get_number_no_bools(&args[0], cell) {")
            lines.append("                Ok(f) => f.trunc() as i32,")
            lines.append("                Err(e) => return Some(e),")
            lines.append("            };")
            lines.append("            let col = match model.get_number_no_bools(&args[1], cell) {")
            lines.append("                Ok(f) => f.trunc() as i32,")
            lines.append("                Err(e) => return Some(e),")
            lines.append("            };")
            lines.append("            if row <= 0 || col <= 0 {")
            lines.append("                return Some(CalcResult::new_error(")
            lines.append("                    Error::VALUE,")
            lines.append("                    cell,")
            lines.append('                    "Row and column must be positive".to_string(),')
            lines.append("                ));")
            lines.append("            }")
            lines.append("            let abs_num = if arg_count >= 3 {")
            lines.append("                match model.get_number_no_bools(&args[2], cell) {")
            lines.append("                    Ok(f) => f.trunc() as i32,")
            lines.append("                    Err(e) => return Some(e),")
            lines.append("                }")
            lines.append("            } else {")
            lines.append("                1")
            lines.append("            };")
            lines.append("            let use_a1 = if arg_count >= 4 {")
            lines.append("                match model.get_boolean(&args[3], cell) {")
            lines.append("                    Ok(b) => b,")
            lines.append("                    Err(e) => return Some(e),")
            lines.append("                }")
            lines.append("            } else {")
            lines.append("                true")
            lines.append("            };")
            lines.append("            if !use_a1 {")
            lines.append("                return Some(CalcResult::new_error(")
            lines.append("                    Error::NIMPL,")
            lines.append("                    cell,")
            lines.append('                    "R1C1 addressing not implemented".to_string(),')
            lines.append("                ));")
            lines.append("            }")
            lines.append("            let column = match number_to_column(col) {")
            lines.append("                Some(c) => c,")
            lines.append("                None => {")
            lines.append("                    return Some(CalcResult::new_error(")
            lines.append("                        Error::VALUE,")
            lines.append("                        cell,")
            lines.append('                        "Invalid column".to_string(),')
            lines.append("                    ))")
            lines.append("                }")
            lines.append("            };")
            lines.append("            let (col_prefix, row_prefix) = match abs_num {")
            lines.append("                1 => (\"$\", \"$\"),")
            lines.append("                2 => (\"\", \"$\"),")
            lines.append("                3 => (\"$\", \"\"),")
            lines.append("                4 => (\"\", \"\"),")
            lines.append("                _ => {")
            lines.append("                    return Some(CalcResult::new_error(")
            lines.append("                        Error::VALUE,")
            lines.append("                        cell,")
            lines.append('                        "Invalid abs_num".to_string(),')
            lines.append("                    ))")
            lines.append("                }")
            lines.append("            };")
            lines.append("            let mut address = format!(\"{col_prefix}{column}{row_prefix}{row}\");")
            lines.append("            if arg_count == 5 {")
            lines.append("                let sheet_text = match model.get_string(&args[4], cell) {")
            lines.append("                    Ok(s) => s,")
            lines.append("                    Err(e) => return Some(e),")
            lines.append("                };")
            lines.append("                if !sheet_text.is_empty() {")
            lines.append("                    address = format!(\"{sheet_text}!{address}\");")
            lines.append("                }")
            lines.append("            }")
            lines.append("            Some(CalcResult::String(address))")
            lines.append("        }")
        elif action == "array_constrain":
            lines.append(f'        "{normalized}" => {{')
            lines.append("            if args.len() != 3 {")
            lines.append("                return Some(CalcResult::new_args_number_error(cell));")
            lines.append("            }")
            lines.append("            let rows = match model.get_number_no_bools(&args[1], cell) {")
            lines.append("                Ok(f) => f.trunc() as i32,")
            lines.append("                Err(e) => return Some(e),")
            lines.append("            };")
            lines.append("            let cols = match model.get_number_no_bools(&args[2], cell) {")
            lines.append("                Ok(f) => f.trunc() as i32,")
            lines.append("                Err(e) => return Some(e),")
            lines.append("            };")
            lines.append("            if rows <= 0 || cols <= 0 {")
            lines.append("                return Some(CalcResult::new_error(")
            lines.append("                    Error::VALUE,")
            lines.append("                    cell,")
            lines.append('                    "Rows and columns must be positive".to_string(),')
            lines.append("                ));")
            lines.append("            }")
            lines.append("            let array = match model.get_number_or_array(&args[0], cell) {")
            lines.append("                Ok(NumberOrArray::Number(f)) => vec![vec![ArrayNode::Number(f)]],")
            lines.append("                Ok(NumberOrArray::Array(a)) => a,")
            lines.append("                Err(e) => return Some(e),")
            lines.append("            };")
            lines.append("            let row_limit = rows as usize;")
            lines.append("            let col_limit = cols as usize;")
            lines.append("            let mut out = Vec::new();")
            lines.append("            for row in array.into_iter().take(row_limit) {")
            lines.append("                let mut out_row = Vec::new();")
            lines.append("                for value in row.into_iter().take(col_limit) {")
            lines.append("                    out_row.push(value);")
            lines.append("                }")
            lines.append("                out.push(out_row);")
            lines.append("            }")
            lines.append("            Some(CalcResult::Array(out))")
            lines.append("        }")
        elif action == "asc":
            lines.append(f'        "{normalized}" => {{')
            lines.append("            if args.len() != 1 {")
            lines.append("                return Some(CalcResult::new_args_number_error(cell));")
            lines.append("            }")
            lines.append("            let text = match model.get_string(&args[0], cell) {")
            lines.append("                Ok(s) => s,")
            lines.append("                Err(e) => return Some(e),")
            lines.append("            };")
            lines.append("            let mut out = String::new();")
            lines.append("            for ch in text.chars() {")
            lines.append("                let code = ch as u32;")
            lines.append("                if code == 0x3000 {")
            lines.append("                    out.push(' ');")
            lines.append("                } else if (0xFF01..=0xFF5E).contains(&code) {")
            lines.append("                    let mapped = char::from_u32(code - 0xFEE0).unwrap_or(ch);")
            lines.append("                    out.push(mapped);")
            lines.append("                } else {")
            lines.append("                    out.push(ch);")
            lines.append("                }")
            lines.append("            }")
            lines.append("            Some(CalcResult::String(out))")
            lines.append("        }")
        elif action == "average_weighted":
            lines.append(f'        "{normalized}" => {{')
            lines.append("            if args.len() < 2 || args.len() % 2 != 0 {")
            lines.append("                return Some(CalcResult::new_args_number_error(cell));")
            lines.append("            }")
            lines.append("            let mut weighted_sum = 0.0;")
            lines.append("            let mut total_weight = 0.0;")
            lines.append("            let mut pair_idx = 0;")
            lines.append("            while pair_idx < args.len() {")
            lines.append("                let values = match model.get_number_or_array(&args[pair_idx], cell) {")
            lines.append("                    Ok(NumberOrArray::Number(f)) => vec![Some(f)],")
            lines.append("                    Ok(NumberOrArray::Array(a)) => match model.values_from_array(a) {")
            lines.append("                        Ok(v) => v,")
            lines.append("                        Err(e) => {")
            lines.append("                            return Some(CalcResult::new_error(")
            lines.append("                                e,")
            lines.append("                                cell,")
            lines.append("                                \"Error in values array\".to_string(),")
            lines.append("                            ))")
            lines.append("                        }")
            lines.append("                    },")
            lines.append("                    Err(e) => return Some(e),")
            lines.append("                };")
            lines.append("                let weights = match model.get_number_or_array(&args[pair_idx + 1], cell) {")
            lines.append("                    Ok(NumberOrArray::Number(f)) => vec![Some(f)],")
            lines.append("                    Ok(NumberOrArray::Array(a)) => match model.values_from_array(a) {")
            lines.append("                        Ok(v) => v,")
            lines.append("                        Err(e) => {")
            lines.append("                            return Some(CalcResult::new_error(")
            lines.append("                                e,")
            lines.append("                                cell,")
            lines.append("                                \"Error in weights array\".to_string(),")
            lines.append("                            ))")
            lines.append("                        }")
            lines.append("                    },")
            lines.append("                    Err(e) => return Some(e),")
            lines.append("                };")
            lines.append("                if values.len() != weights.len() {")
            lines.append("                    return Some(CalcResult::new_error(")
            lines.append("                        Error::VALUE,")
            lines.append("                        cell,")
            lines.append('                        "Values and weights must have the same length".to_string(),')
            lines.append("                    ));")
            lines.append("                }")
            lines.append("                for idx in 0..values.len() {")
            lines.append("                    if let (Some(v), Some(w)) = (values[idx], weights[idx]) {")
            lines.append("                        weighted_sum += v * w;")
            lines.append("                        total_weight += w;")
            lines.append("                    }")
            lines.append("                }")
            lines.append("                pair_idx += 2;")
            lines.append("            }")
            lines.append("            if total_weight == 0.0 {")
            lines.append("                return Some(CalcResult::new_error(")
            lines.append("                    Error::DIV,")
            lines.append("                    cell,")
            lines.append('                    "Total weight is zero".to_string(),')
            lines.append("                ));")
            lines.append("            }")
            lines.append("            Some(CalcResult::Number(weighted_sum / total_weight))")
            lines.append("        }")
        else:
            raise SystemExit(f"Unknown action: {action} for {name}")
    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_tests_rs(rows: List[Dict[str, str]]) -> str:
    unimplemented = [
        r["function_name"] for r in rows if r.get("action") == "unimplemented"
    ]
    fallback_rows = [
        r
        for r in rows
        if r.get("action")
        not in ("unimplemented", "implemented", None, "")
    ]

    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_batch_fallbacks.py")
    lines.append("// Do not edit by hand.")
    lines.append("#![allow(clippy::unwrap_used)]")
    lines.append("")
    lines.append("use crate::test::util::new_empty_model;")
    lines.append("")
    lines.append("#[test]")
    lines.append("fn test_batch_unsupported_functions_return_nimpl() {")
    lines.append("    let mut model = new_empty_model();")
    lines.append("    let functions = [")
    for name in unimplemented:
        lines.append(f'        "{name}",')
    lines.append("    ];")
    lines.append("")
    lines.append("    for (idx, function) in functions.iter().enumerate() {")
    lines.append("        let cell = format!(\"A{}\", idx + 1);")
    lines.append("        model._set(&cell, &format!(\"={function}(1)\"));")
    lines.append("    }")
    lines.append("    model.evaluate();")
    lines.append("")
    lines.append("    for row in 1..=functions.len() as i32 {")
    lines.append("        let cell = format!(\"A{row}\");")
    lines.append("        assert_eq!(model._get_text(&cell), *\"#N/IMPL!\");")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#[test]")
    lines.append("fn test_unknown_function_returns_name_error() {")
    lines.append("    let mut model = new_empty_model();")
    lines.append("    model._set(\"A1\", \"=NOT_A_FUNCTION(1)\");")
    lines.append("    model.evaluate();")
    lines.append("")
    lines.append("    assert_eq!(model._get_text(\"A1\"), *\"#NAME?\");")
    lines.append("}")

    for row in fallback_rows:
        name = row["function_name"]
        test_name = sanitize_test_name(name)
        test_cell = row.get("test_cell", "").strip() or "A1"
        test_formula = row.get("test_formula", "").strip()
        expected_text = row.get("expected_text", "").strip()
        setup = row.get("setup", "").strip()
        test_cell_2 = (row.get("test_cell_2") or "").strip()
        test_formula_2 = (row.get("test_formula_2") or "").strip()
        expected_text_2 = (row.get("expected_text_2") or "").strip()
        setup_2 = (row.get("setup_2") or "").strip()
        if not test_formula or not expected_text:
            raise SystemExit(f"Missing test_formula/expected_text for {name}")
        lines.append("")
        lines.append("#[test]")
        lines.append(f"fn test_batch_fallback_{test_name}() {{")
        lines.append("    let mut model = new_empty_model();")
        if setup:
            for assignment in setup.split(";"):
                assignment = assignment.strip()
                if not assignment:
                    continue
                cell, value = assignment.split("=", 1)
                lines.append(
                    f"    model._set(\"{escape_rust_string(cell)}\", \"{escape_rust_string(value)}\");"
                )
        lines.append(
            f"    model._set(\"{escape_rust_string(test_cell)}\", \"{escape_rust_string(test_formula)}\");"
        )
        lines.append("    model.evaluate();")
        lines.append("")
        lines.append(
            f"    assert_eq!(model._get_text(\"{escape_rust_string(test_cell)}\"), *\"{escape_rust_string(expected_text)}\");"
        )
        lines.append("}")
        if test_formula_2 and expected_text_2:
            lines.append("")
            lines.append("#[test]")
            lines.append(f"fn test_batch_fallback_{test_name}_extra() {{")
            lines.append("    let mut model = new_empty_model();")
            if setup_2:
                for assignment in setup_2.split(";"):
                    assignment = assignment.strip()
                    if not assignment:
                        continue
                    cell, value = assignment.split("=", 1)
                    lines.append(
                        f"    model._set(\"{escape_rust_string(cell)}\", \"{escape_rust_string(value)}\");"
                    )
            lines.append(
                f"    model._set(\"{escape_rust_string(test_cell_2 or 'A1')}\", \"{escape_rust_string(test_formula_2)}\");"
            )
            lines.append("    model.evaluate();")
            lines.append("")
            lines.append(
                f"    assert_eq!(model._get_text(\"{escape_rust_string(test_cell_2 or 'A1')}\"), *\"{escape_rust_string(expected_text_2)}\");"
            )
            lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate batch fallback code and tests.")
    parser.add_argument("--batch", type=str, default="all")
    args = parser.parse_args()

    rows = load_rows(args.batch)
    OUT_FALLBACKS_RS.write_text(gen_fallbacks_rs(rows))
    OUT_TEST_RS.write_text(gen_tests_rs(rows))
    print(f"Wrote {OUT_FALLBACKS_RS}")
    print(f"Wrote {OUT_TEST_RS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
