#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import List


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HF = ROOT / "specs" / "matrices" / "hyperformula_functions.csv"
DEFAULT_MATRIX = ROOT / "specs" / "matrices" / "function_matrix.csv"
DEFAULT_MATRIX_NORM = ROOT / "specs" / "matrices" / "function_matrix_normalized.csv"
DEFAULT_MD = ROOT / "specs" / "matrices" / "function_matrix.md"


def load_hf(path: Path) -> set[str]:
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        return {row["function_name"].strip().upper() for row in reader if row.get("function_name")}


def update_matrix(path: Path, hf_funcs: set[str]) -> None:
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        fieldnames = list(reader.fieldnames or [])

    if "HyperFormula" not in fieldnames:
        if "Origin" in fieldnames:
            idx = fieldnames.index("Origin")
            fieldnames.insert(idx, "HyperFormula")
        else:
            fieldnames.append("HyperFormula")

    for row in rows:
        func = (row.get("Function") or "").strip().upper()
        row["HyperFormula"] = "Y" if func in hf_funcs else "N"

    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def count_yes(rows: List[dict], column: str) -> int:
    return sum(1 for r in rows if r.get(column, "").strip().upper() == "Y")


def update_md(md_path: Path, matrix_path: Path) -> None:
    with matrix_path.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    total = len(rows)
    ironcalc = count_yes(rows, "IronCalc")
    excel = count_yes(rows, "Excel")
    sheets = count_yes(rows, "GoogleSheets")
    hyper = count_yes(rows, "HyperFormula")

    iron_in_excel = sum(
        1 for r in rows if r.get("IronCalc", "") == "Y" and r.get("Excel", "") == "Y"
    )
    iron_in_sheets = sum(
        1 for r in rows if r.get("IronCalc", "") == "Y" and r.get("GoogleSheets", "") == "Y"
    )
    hyper_in_excel = sum(
        1 for r in rows if r.get("HyperFormula", "") == "Y" and r.get("Excel", "") == "Y"
    )
    hyper_in_sheets = sum(
        1
        for r in rows
        if r.get("HyperFormula", "") == "Y" and r.get("GoogleSheets", "") == "Y"
    )
    excel_missing_iron = sum(
        1 for r in rows if r.get("Excel", "") == "Y" and r.get("IronCalc", "") != "Y"
    )
    sheets_missing_iron = sum(
        1 for r in rows if r.get("GoogleSheets", "") == "Y" and r.get("IronCalc", "") != "Y"
    )
    excel_missing_hyper = sum(
        1
        for r in rows
        if r.get("Excel", "") == "Y" and r.get("HyperFormula", "") != "Y"
    )
    sheets_missing_hyper = sum(
        1
        for r in rows
        if r.get("GoogleSheets", "") == "Y" and r.get("HyperFormula", "") != "Y"
    )

    content = (
        "# Function Coverage Matrix\n\n"
        "Generated by `scripts/update_function_matrix.py`.\n\n"
        "## Summary\n"
        f"- Total unique functions (union): {total}\n"
        f"- IronCalc functions: {ironcalc}\n"
        f"- Excel functions: {excel}\n"
        f"- Google Sheets functions: {sheets}\n"
        f"- HyperFormula functions: {hyper}\n"
        f"- IronCalc in Excel: {iron_in_excel}\n"
        f"- IronCalc in Sheets: {iron_in_sheets}\n"
        f"- HyperFormula in Excel: {hyper_in_excel}\n"
        f"- HyperFormula in Sheets: {hyper_in_sheets}\n"
        f"- Excel functions missing in IronCalc: {excel_missing_iron}\n"
        f"- Sheets functions missing in IronCalc: {sheets_missing_iron}\n"
        f"- Excel functions missing in HyperFormula: {excel_missing_hyper}\n"
        f"- Sheets functions missing in HyperFormula: {sheets_missing_hyper}\n\n"
        "## Full Matrix\n\n"
        "See `specs/matrices/function_matrix.csv` for the complete list.\n"
    )
    md_path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser(description="Update function matrix with HyperFormula coverage.")
    parser.add_argument("--hf", default=str(DEFAULT_HF), help="HyperFormula functions CSV")
    parser.add_argument("--matrix", default=str(DEFAULT_MATRIX), help="Full matrix CSV")
    parser.add_argument(
        "--matrix-normalized",
        default=str(DEFAULT_MATRIX_NORM),
        help="Normalized matrix CSV",
    )
    parser.add_argument("--md", default=str(DEFAULT_MD), help="Matrix markdown summary")
    args = parser.parse_args()

    hf_funcs = load_hf(Path(args.hf))
    update_matrix(Path(args.matrix), hf_funcs)
    update_matrix(Path(args.matrix_normalized), hf_funcs)
    update_md(Path(args.md), Path(args.matrix))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
