// AUTO-GENERATED by scripts/generate_batch_fallbacks.py
// Do not edit by hand.
#![allow(clippy::unwrap_used)]

use crate::test::util::new_empty_model;

#[test]
fn test_batch_unsupported_functions_return_nimpl() {
    let mut model = new_empty_model();
    let functions: [&str; 0] = [];

    for (idx, function) in functions.iter().enumerate() {
        let cell = format!("A{}", idx + 1);
        model._set(&cell, &format!("={function}(1)"));
    }
    model.evaluate();

    for row in 1..=functions.len() as i32 {
        let cell = format!("A{row}");
        assert_eq!(model._get_text(&cell), *"#N/IMPL!");
    }
}

#[test]
fn test_unknown_function_returns_name_error() {
    let mut model = new_empty_model();
    model._set("A1", "=NOT_A_FUNCTION(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#NAME?");
}

#[test]
fn test_batch_fallback_accrint() {
    let mut model = new_empty_model();
    model._set("A1", "=ACCRINT(1,2,37,0.1,100,1,0)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"1");
}

#[test]
fn test_batch_fallback_accrintm() {
    let mut model = new_empty_model();
    model._set("A1", "=ACCRINTM(1,37,0.1,100,0)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"1");
}

#[test]
fn test_batch_fallback_add() {
    let mut model = new_empty_model();
    model._set("A1", "=ADD(1,2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"6");
}

#[test]
fn test_batch_fallback_add_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ADD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"#ERROR!");
}

#[test]
fn test_batch_fallback_address() {
    let mut model = new_empty_model();
    model._set("A1", "=ADDRESS(2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"$C$2");
}

#[test]
fn test_batch_fallback_address_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ADDRESS(2,3,4)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"C2");
}

#[test]
fn test_batch_fallback_aggregate() {
    let mut model = new_empty_model();
    model._set("A1", "=AGGREGATE(9,0,1,2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"6");
}

#[test]
fn test_batch_fallback_aggregate_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=AGGREGATE(1,0,1,2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"2");
}

#[test]
fn test_batch_fallback_amordegrc() {
    let mut model = new_empty_model();
    model._set("A1", "=AMORDEGRC(1000,1,2,100,2,0.1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"81");
}

#[test]
fn test_batch_fallback_amorlinc() {
    let mut model = new_empty_model();
    model._set("A1", "=AMORLINC(1000,1,2,100,2,0.1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"90");
}

#[test]
fn test_batch_fallback_areas() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("B1", "=AREAS(A1:A2)");
    model.evaluate();

    assert_eq!(model._get_text("B1"), *"1");
}

#[test]
fn test_batch_fallback_arrayformula() {
    let mut model = new_empty_model();
    model._set("A1", "=ARRAYFORMULA(1+2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"3");
}

#[test]
fn test_batch_fallback_array_constrain() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(ARRAY_CONSTRAIN({1,2;3,4;5,6},2,1))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"4");
}

#[test]
fn test_batch_fallback_asc() {
    let mut model = new_empty_model();
    model._set("A1", "=ASC(\"ＡＢＣ\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"ABC");
}

#[test]
fn test_batch_fallback_average_weighted() {
    let mut model = new_empty_model();
    model._set("A1", "=AVERAGE.WEIGHTED({10,20,30},{1,2,3})");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"23.333333333");
}

#[test]
fn test_batch_fallback_bahttext() {
    let mut model = new_empty_model();
    model._set("A1", "=BAHTTEXT(123)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"123 BAHT");
}

#[test]
fn test_batch_fallback_beta_invn() {
    let mut model = new_empty_model();
    model._set("A1", "=BETA.INVN(0.5,2,2,0,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"0.5");
}

#[test]
fn test_batch_fallback_bycol() {
    let mut model = new_empty_model();
    model._set("A1", "=BYCOL(A1:B2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_byrow() {
    let mut model = new_empty_model();
    model._set("A1", "=BYROW(A1:B2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_call() {
    let mut model = new_empty_model();
    model._set("A1", "=CALL(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_char() {
    let mut model = new_empty_model();
    model._set("A1", "=CHAR(65)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"A");
}

#[test]
fn test_batch_fallback_choosecols() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(CHOOSECOLS({1,2;3,4},2))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"6");
}

#[test]
fn test_batch_fallback_choosecols_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(CHOOSECOLS({1,2,3;4,5,6},-1))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"9");
}

#[test]
fn test_batch_fallback_chooserows() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(CHOOSEROWS({1,2;3,4},2))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"7");
}

#[test]
fn test_batch_fallback_chooserows_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(CHOOSEROWS({1,2;3,4},-1))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"7");
}

#[test]
fn test_batch_fallback_clean() {
    let mut model = new_empty_model();
    model._set("A1", "=CLEAN(\"A\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"A");
}

#[test]
fn test_batch_fallback_code() {
    let mut model = new_empty_model();
    model._set("A1", "=CODE(\"A\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"65");
}

#[test]
fn test_batch_fallback_copilot() {
    let mut model = new_empty_model();
    model._set("A1", "=COPILOT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_countunique() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("A3", "2");
    model._set("A4", "3");
    model._set("B1", "=COUNTUNIQUE(A1:A4)");
    model.evaluate();

    assert_eq!(model._get_text("B1"), *"3");
}

#[test]
fn test_batch_fallback_coupdaybs() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPDAYBS(1,2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupdays() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPDAYS(1,2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupdaysnc() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPDAYSNC(1,2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupncd() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPNCD(1,2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupnum() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPNUM(1,2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_couppcd() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPPCD(1,2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_critbinom() {
    let mut model = new_empty_model();
    model._set("A1", "=CRITBINOM(10,0.5,0.5)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"5");
}

#[test]
fn test_batch_fallback_cubekpimember() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEKPIMEMBER(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubemember() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEMEMBER(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubememberproperty() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEMEMBERPROPERTY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cuberankedmember() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBERANKEDMEMBER(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubeset() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBESET(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubesetcount() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBESETCOUNT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubevalue() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEVALUE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_dbcs() {
    let mut model = new_empty_model();
    model._set("A1", "=DBCS(\"ABC\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"ＡＢＣ");
}

#[test]
fn test_batch_fallback_detectlanguage() {
    let mut model = new_empty_model();
    model._set("A1", "=DETECTLANGUAGE(\"Hello\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"en");
}

#[test]
fn test_batch_fallback_disc() {
    let mut model = new_empty_model();
    model._set("A1", "=DISC(1,361,50,100)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"0.5");
}

#[test]
fn test_batch_fallback_divide() {
    let mut model = new_empty_model();
    model._set("A1", "=DIVIDE(10,2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"5");
}

#[test]
fn test_batch_fallback_divide_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=DIVIDE(1,0)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"#DIV/0!");
}

#[test]
fn test_batch_fallback_dollar() {
    let mut model = new_empty_model();
    model._set("A1", "=DOLLAR(1234.5)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"$1,234.50");
}

#[test]
fn test_batch_fallback_dollar_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=DOLLAR(1.236,1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"$1.2");
}

#[test]
fn test_batch_fallback_drop() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(DROP({1,2;3,4},1,1))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"4");
}

#[test]
fn test_batch_fallback_drop_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(DROP({1,2;3,4},-1,-1))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"1");
}

#[test]
fn test_batch_fallback_duration() {
    let mut model = new_empty_model();
    model._set("A1", "=DURATION(1,2,0.1,0.1,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_encodeurl() {
    let mut model = new_empty_model();
    model._set("A1", "=ENCODEURL(\"https://example.com/hello world\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"https%3A%2F%2Fexample.com%2Fhello%20world");
}

#[test]
fn test_batch_fallback_epochtodate() {
    let mut model = new_empty_model();
    model._set("A1", "=EPOCHTODATE(0)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"25569");
}

#[test]
fn test_batch_fallback_epochtodate_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=EPOCHTODATE(86400)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"25570");
}

#[test]
fn test_batch_fallback_eq() {
    let mut model = new_empty_model();
    model._set("A1", "=EQ(1,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_eq_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=EQ(1,2)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_euroconvert() {
    let mut model = new_empty_model();
    model._set("A1", "=EUROCONVERT(1,\"EUR\",\"USD\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_expand() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(EXPAND({1,2},2,3,0))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"3");
}

#[test]
fn test_batch_fallback_filter() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("A3", "3");
    model._set("B1", "TRUE");
    model._set("B2", "FALSE");
    model._set("B3", "TRUE");
    model._set("C1", "=SUM(FILTER(A1:A3,B1:B3))");
    model.evaluate();

    assert_eq!(model._get_text("C1"), *"4");
}

#[test]
fn test_batch_fallback_filterxml() {
    let mut model = new_empty_model();
    model._set("A1", "=FILTERXML(\"<a>1</a>\",\"//a\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_findb() {
    let mut model = new_empty_model();
    model._set("A1", "=FINDB(\"b\",\"abc\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"2");
}

#[test]
fn test_batch_fallback_fixed() {
    let mut model = new_empty_model();
    model._set("A1", "=FIXED(1234.567,2,FALSE)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"1,234.57");
}

#[test]
fn test_batch_fallback_flatten() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(FLATTEN({1,2;3,4}))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_forecast() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("A3", "3");
    model._set("B1", "1");
    model._set("B2", "2");
    model._set("B3", "3");
    model._set("C1", "=FORECAST(4,A1:A3,B1:B3)");
    model.evaluate();

    assert_eq!(model._get_text("C1"), *"4");
}

#[test]
fn test_batch_fallback_forecast_ets() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS(1,1,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_ets_confint() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS.CONFINT(1,1,1,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_ets_seasonality() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS.SEASONALITY(1,1,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_ets_stat() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS.STAT(1,1,1,1,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_linear() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("A3", "3");
    model._set("B1", "1");
    model._set("B2", "2");
    model._set("B3", "3");
    model._set("C1", "=FORECAST.LINEAR(5,A1:A3,B1:B3)");
    model.evaluate();

    assert_eq!(model._get_text("C1"), *"5");
}

#[test]
fn test_batch_fallback_frequency() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(FREQUENCY({1,2,3,4,5},{2,4}))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"5");
}

#[test]
fn test_batch_fallback_fvschedule() {
    let mut model = new_empty_model();
    model._set("A1", "=FVSCHEDULE(100,{0.1,0.2})");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"132");
}

#[test]
fn test_batch_fallback_getpivotdata() {
    let mut model = new_empty_model();
    model._set("A1", "=GETPIVOTDATA(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_googlefinance() {
    let mut model = new_empty_model();
    model._set("A1", "=GOOGLEFINANCE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_googletranslate() {
    let mut model = new_empty_model();
    model._set("A1", "=GOOGLETRANSLATE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_groupby() {
    let mut model = new_empty_model();
    model._set("A1", "=GROUPBY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_growth() {
    let mut model = new_empty_model();
    model._set("A1", "=GROWTH(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_gt() {
    let mut model = new_empty_model();
    model._set("A1", "=GT(5,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_gt_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=GT(2,2)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_gte() {
    let mut model = new_empty_model();
    model._set("A1", "=GTE(2,2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_gte_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=GTE(1,2)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_hstack() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(HSTACK({1,2},{3,4}))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_hstack_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(HSTACK({1,2;3,4},{5,6;7,8}))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"36");
}

#[test]
fn test_batch_fallback_hyperlink() {
    let mut model = new_empty_model();
    model._set("A1", "=HYPERLINK(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_image() {
    let mut model = new_empty_model();
    model._set("A1", "=IMAGE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_imcoth() {
    let mut model = new_empty_model();
    model._set("A1", "=IMCOTH(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_imlog() {
    let mut model = new_empty_model();
    model._set("A1", "=IMLOG(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_importdata() {
    let mut model = new_empty_model();
    model._set("A1", "=IMPORTDATA(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_importfeed() {
    let mut model = new_empty_model();
    model._set("A1", "=IMPORTFEED(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_importhtml() {
    let mut model = new_empty_model();
    model._set("A1", "=IMPORTHTML(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_importrange() {
    let mut model = new_empty_model();
    model._set("A1", "=IMPORTRANGE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_importxml() {
    let mut model = new_empty_model();
    model._set("A1", "=IMPORTXML(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_imtanh() {
    let mut model = new_empty_model();
    model._set("A1", "=IMTANH(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_intrate() {
    let mut model = new_empty_model();
    model._set("A1", "=INTRATE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_isbetween() {
    let mut model = new_empty_model();
    model._set("A1", "=ISBETWEEN(5,1,10)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_isbetween_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ISBETWEEN(5,1,4)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_isdate() {
    let mut model = new_empty_model();
    model._set("A1", "=ISDATE(\"2024-02-29\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_isdate_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ISDATE(\"not a date\")");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_isemail() {
    let mut model = new_empty_model();
    model._set("A1", "=ISEMAIL(\"test@example.com\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_isemail_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ISEMAIL(\"bad-email\")");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_isomitted() {
    let mut model = new_empty_model();
    model._set("A1", "=ISOMITTED(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"FALSE");
}

#[test]
fn test_batch_fallback_isurl() {
    let mut model = new_empty_model();
    model._set("A1", "=ISURL(\"https://example.com\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_isurl_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ISURL(\"not a url\")");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_jis() {
    let mut model = new_empty_model();
    model._set("A1", "=JIS(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_join() {
    let mut model = new_empty_model();
    model._set("A1", "=JOIN(\",\",1,2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"1,2,3");
}

#[test]
fn test_batch_fallback_join_extra() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "=JOIN(\"-\",A1:A1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"1");
}

#[test]
fn test_batch_fallback_lambda() {
    let mut model = new_empty_model();
    model._set("A1", "=LAMBDA(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_leftb() {
    let mut model = new_empty_model();
    model._set("A1", "=LEFTB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_lenb() {
    let mut model = new_empty_model();
    model._set("A1", "=LENB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_let() {
    let mut model = new_empty_model();
    model._set("A1", "=LET(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_linest() {
    let mut model = new_empty_model();
    model._set("A1", "=LINEST(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_logest() {
    let mut model = new_empty_model();
    model._set("A1", "=LOGEST(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_lt() {
    let mut model = new_empty_model();
    model._set("A1", "=LT(1,2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_lt_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=LT(2,1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_lte() {
    let mut model = new_empty_model();
    model._set("A1", "=LTE(2,2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_lte_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=LTE(3,2)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_makearray() {
    let mut model = new_empty_model();
    model._set("A1", "=MAKEARRAY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_map() {
    let mut model = new_empty_model();
    model._set("A1", "=MAP(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_marginoferror() {
    let mut model = new_empty_model();
    model._set("A1", "=MARGINOFERROR(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_mdeterm() {
    let mut model = new_empty_model();
    model._set("A1", "=MDETERM(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_mduration() {
    let mut model = new_empty_model();
    model._set("A1", "=MDURATION(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_midb() {
    let mut model = new_empty_model();
    model._set("A1", "=MIDB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_minus() {
    let mut model = new_empty_model();
    model._set("A1", "=MINUS(5,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"2");
}

#[test]
fn test_batch_fallback_minus_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=MINUS(3,5)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"-2");
}

#[test]
fn test_batch_fallback_minverse() {
    let mut model = new_empty_model();
    model._set("A1", "=MINVERSE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_mmult() {
    let mut model = new_empty_model();
    model._set("A1", "=MMULT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_mode() {
    let mut model = new_empty_model();
    model._set("A1", "=MODE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_mode_mult() {
    let mut model = new_empty_model();
    model._set("A1", "=MODE.MULT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_mode_sngl() {
    let mut model = new_empty_model();
    model._set("A1", "=MODE.SNGL(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_multinomial() {
    let mut model = new_empty_model();
    model._set("A1", "=MULTINOMIAL(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_multiply() {
    let mut model = new_empty_model();
    model._set("A1", "=MULTIPLY(2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"6");
}

#[test]
fn test_batch_fallback_multiply_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=MULTIPLY(-2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"-6");
}

#[test]
fn test_batch_fallback_munit() {
    let mut model = new_empty_model();
    model._set("A1", "=MUNIT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_ne() {
    let mut model = new_empty_model();
    model._set("A1", "=NE(1,2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_ne_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=NE(2,2)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_numbervalue() {
    let mut model = new_empty_model();
    model._set("A1", "=NUMBERVALUE(\"1,234.5\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"1234.5");
}

#[test]
fn test_batch_fallback_numbervalue_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=NUMBERVALUE(\"123\")");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"123");
}

#[test]
fn test_batch_fallback_oddfprice() {
    let mut model = new_empty_model();
    model._set("A1", "=ODDFPRICE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_oddfyield() {
    let mut model = new_empty_model();
    model._set("A1", "=ODDFYIELD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_oddlprice() {
    let mut model = new_empty_model();
    model._set("A1", "=ODDLPRICE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_oddlyield() {
    let mut model = new_empty_model();
    model._set("A1", "=ODDLYIELD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_percentile() {
    let mut model = new_empty_model();
    model._set("A1", "=PERCENTILE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_percentile_exc() {
    let mut model = new_empty_model();
    model._set("A1", "=PERCENTILE.EXC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_percentile_inc() {
    let mut model = new_empty_model();
    model._set("A1", "=PERCENTILE.INC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_percentrank() {
    let mut model = new_empty_model();
    model._set("A1", "=PERCENTRANK(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_percentrank_exc() {
    let mut model = new_empty_model();
    model._set("A1", "=PERCENTRANK.EXC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_percentrank_inc() {
    let mut model = new_empty_model();
    model._set("A1", "=PERCENTRANK.INC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_permut() {
    let mut model = new_empty_model();
    model._set("A1", "=PERMUT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_permutationa() {
    let mut model = new_empty_model();
    model._set("A1", "=PERMUTATIONA(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_phonetic() {
    let mut model = new_empty_model();
    model._set("A1", "=PHONETIC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_pivotby() {
    let mut model = new_empty_model();
    model._set("A1", "=PIVOTBY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_pow() {
    let mut model = new_empty_model();
    model._set("A1", "=POW(2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"8");
}

#[test]
fn test_batch_fallback_pow_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=POW(9,0.5)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"3");
}

#[test]
fn test_batch_fallback_price() {
    let mut model = new_empty_model();
    model._set("A1", "=PRICE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_pricedisc() {
    let mut model = new_empty_model();
    model._set("A1", "=PRICEDISC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_pricemat() {
    let mut model = new_empty_model();
    model._set("A1", "=PRICEMAT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_prob() {
    let mut model = new_empty_model();
    model._set("A1", "=PROB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_proper() {
    let mut model = new_empty_model();
    model._set("A1", "=PROPER(\"hello world\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"Hello World");
}

#[test]
fn test_batch_fallback_proper_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=PROPER(\"mIxEd\")");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"Mixed");
}

#[test]
fn test_batch_fallback_quartile() {
    let mut model = new_empty_model();
    model._set("A1", "=QUARTILE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_quartile_exc() {
    let mut model = new_empty_model();
    model._set("A1", "=QUARTILE.EXC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_quartile_inc() {
    let mut model = new_empty_model();
    model._set("A1", "=QUARTILE.INC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_query() {
    let mut model = new_empty_model();
    model._set("A1", "=QUERY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_randarray() {
    let mut model = new_empty_model();
    model._set("A1", "=RANDARRAY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_rank() {
    let mut model = new_empty_model();
    model._set("A1", "=RANK(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_received() {
    let mut model = new_empty_model();
    model._set("A1", "=RECEIVED(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_reduce() {
    let mut model = new_empty_model();
    model._set("A1", "=REDUCE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_regexextract() {
    let mut model = new_empty_model();
    model._set("A1", "=REGEXEXTRACT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_regexmatch() {
    let mut model = new_empty_model();
    model._set("A1", "=REGEXMATCH(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_regexreplace() {
    let mut model = new_empty_model();
    model._set("A1", "=REGEXREPLACE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_register_id() {
    let mut model = new_empty_model();
    model._set("A1", "=REGISTER.ID(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_replace() {
    let mut model = new_empty_model();
    model._set("A1", "=REPLACE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_replaceb() {
    let mut model = new_empty_model();
    model._set("A1", "=REPLACEB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_rightb() {
    let mut model = new_empty_model();
    model._set("A1", "=RIGHTB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_rtd() {
    let mut model = new_empty_model();
    model._set("A1", "=RTD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_scan() {
    let mut model = new_empty_model();
    model._set("A1", "=SCAN(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_searchb() {
    let mut model = new_empty_model();
    model._set("A1", "=SEARCHB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_sequence() {
    let mut model = new_empty_model();
    model._set("A1", "=SEQUENCE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_seriessum() {
    let mut model = new_empty_model();
    model._set("A1", "=SERIESSUM(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_sort() {
    let mut model = new_empty_model();
    model._set("A1", "=SORT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_sortby() {
    let mut model = new_empty_model();
    model._set("A1", "=SORTBY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_sortn() {
    let mut model = new_empty_model();
    model._set("A1", "=SORTN(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_sparkline() {
    let mut model = new_empty_model();
    model._set("A1", "=SPARKLINE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_split() {
    let mut model = new_empty_model();
    model._set("A1", "=SPLIT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_stockhistory() {
    let mut model = new_empty_model();
    model._set("A1", "=STOCKHISTORY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_sumproduct() {
    let mut model = new_empty_model();
    model._set("A1", "=SUMPRODUCT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_take() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(TAKE({1,2;3,4},1,1))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"1");
}

#[test]
fn test_batch_fallback_take_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(TAKE({1,2;3,4},-1))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"7");
}

#[test]
fn test_batch_fallback_textsplit() {
    let mut model = new_empty_model();
    model._set("A1", "=TEXTSPLIT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_tocol() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(TOCOL({1,2;3,4}))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_torow() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(TOROW({1,2;3,4}))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_to_date() {
    let mut model = new_empty_model();
    model._set("A1", "=TO_DATE(\"2024-02-29\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"45351");
}

#[test]
fn test_batch_fallback_to_dollars() {
    let mut model = new_empty_model();
    model._set("A1", "=TO_DOLLARS(123.45)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"123.45");
}

#[test]
fn test_batch_fallback_to_percent() {
    let mut model = new_empty_model();
    model._set("A1", "=TO_PERCENT(0.5)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"0.5");
}

#[test]
fn test_batch_fallback_to_pure_number() {
    let mut model = new_empty_model();
    model._set("A1", "=TO_PURE_NUMBER(\"1,234.5\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"1234.5");
}

#[test]
fn test_batch_fallback_to_text() {
    let mut model = new_empty_model();
    model._set("A1", "=TO_TEXT(123.45)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"123.45");
}

#[test]
fn test_batch_fallback_transpose() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(TRANSPOSE({1,2;3,4}))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_trend() {
    let mut model = new_empty_model();
    model._set("A1", "=TREND(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_trimmean() {
    let mut model = new_empty_model();
    model._set("A1", "=TRIMMEAN(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_trimrange() {
    let mut model = new_empty_model();
    model._set("A1", "=TRIMRANGE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_uminus() {
    let mut model = new_empty_model();
    model._set("A1", "=UMINUS(3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"-3");
}

#[test]
fn test_batch_fallback_uminus_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=UMINUS(-2)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"2");
}

#[test]
fn test_batch_fallback_unary_percent() {
    let mut model = new_empty_model();
    model._set("A1", "=UNARY_PERCENT(50)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"0.5");
}

#[test]
fn test_batch_fallback_unary_percent_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=UNARY_PERCENT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"0.01");
}

#[test]
fn test_batch_fallback_unichar() {
    let mut model = new_empty_model();
    model._set("A1", "=UNICHAR(65)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"A");
}

#[test]
fn test_batch_fallback_unique() {
    let mut model = new_empty_model();
    model._set("A1", "=UNIQUE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_uplus() {
    let mut model = new_empty_model();
    model._set("A1", "=UPLUS(-3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"-3");
}

#[test]
fn test_batch_fallback_uplus_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=UPLUS(0)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"0");
}

#[test]
fn test_batch_fallback_vdb() {
    let mut model = new_empty_model();
    model._set("A1", "=VDB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_vstack() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(VSTACK({1,2},{3,4}))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_vstack_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(VSTACK({1,2;3,4},{5,6;7,8}))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"36");
}

#[test]
fn test_batch_fallback_webservice() {
    let mut model = new_empty_model();
    model._set("A1", "=WEBSERVICE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_wrapcols() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(WRAPCOLS({1,2,3,4},2))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_wraprows() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(WRAPROWS({1,2,3,4},2))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"10");
}

#[test]
fn test_batch_fallback_xmatch() {
    let mut model = new_empty_model();
    model._set("A1", "=XMATCH(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_yield() {
    let mut model = new_empty_model();
    model._set("A1", "=YIELD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_yielddisc() {
    let mut model = new_empty_model();
    model._set("A1", "=YIELDDISC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_yieldmat() {
    let mut model = new_empty_model();
    model._set("A1", "=YIELDMAT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}
