// AUTO-GENERATED by scripts/generate_batch_fallbacks.py
// Do not edit by hand.
#![allow(clippy::unwrap_used)]

use crate::test::util::new_empty_model;

#[test]
fn test_batch_unsupported_functions_return_nimpl() {
    let mut model = new_empty_model();
    let functions = [
        "ACCRINT",
        "ACCRINTM",
        "AGGREGATE",
        "AMORDEGRC",
        "AMORLINC",
        "BAHTTEXT",
        "BYCOL",
        "BYROW",
        "CALL",
        "CHOOSECOLS",
        "CHOOSEROWS",
        "COPILOT",
        "COUNTUNIQUE",
        "COUPDAYBS",
        "COUPDAYS",
        "COUPDAYSNC",
        "COUPNCD",
        "COUPNUM",
        "COUPPCD",
        "CRITBINOM",
        "CUBEKPIMEMBER",
        "CUBEMEMBER",
        "CUBEMEMBERPROPERTY",
        "CUBERANKEDMEMBER",
        "CUBESET",
        "CUBESETCOUNT",
        "CUBEVALUE",
        "DBCS",
        "DETECTLANGUAGE",
        "DISC",
        "DIVIDE",
        "DOLLAR",
        "DROP",
        "DURATION",
        "ENCODEURL",
        "EPOCHTODATE",
        "EQ",
        "EUROCONVERT",
        "EXPAND",
        "FILTER",
        "FILTERXML",
        "FINDB",
        "FIXED",
        "FLATTEN",
        "FORECAST",
        "FORECAST.ETS",
        "FORECAST.ETS.CONFINT",
        "FORECAST.ETS.SEASONALITY",
        "FORECAST.ETS.STAT",
        "FORECAST.LINEAR",
        "FREQUENCY",
        "FVSCHEDULE",
        "GETPIVOTDATA",
        "GOOGLEFINANCE",
        "GOOGLETRANSLATE",
        "GROUPBY",
        "GROWTH",
        "GT",
        "GTE",
        "HSTACK",
        "HYPERLINK",
        "IMAGE",
        "IMCOTH",
        "IMLOG",
        "IMPORTDATA",
        "IMPORTFEED",
        "IMPORTHTML",
        "IMPORTRANGE",
        "IMPORTXML",
        "IMTANH",
        "INTRATE",
        "ISBETWEEN",
        "ISDATE",
        "ISEMAIL",
        "ISOMITTED",
        "ISURL",
        "JIS",
        "JOIN",
        "LAMBDA",
        "LEFTB",
        "LENB",
        "LET",
        "LINEST",
        "LOGEST",
        "LT",
        "LTE",
        "MAKEARRAY",
        "MAP",
        "MARGINOFERROR",
        "MDETERM",
        "MDURATION",
        "MIDB",
        "MINUS",
        "MINVERSE",
        "MMULT",
        "MODE",
        "MODE.MULT",
        "MODE.SNGL",
        "MULTINOMIAL",
        "MULTIPLY",
        "MUNIT",
        "NE",
        "NUMBERVALUE",
        "ODDFPRICE",
        "ODDFYIELD",
        "ODDLPRICE",
        "ODDLYIELD",
        "PERCENTILE",
        "PERCENTILE.EXC",
        "PERCENTILE.INC",
        "PERCENTRANK",
        "PERCENTRANK.EXC",
        "PERCENTRANK.INC",
        "PERMUT",
        "PERMUTATIONA",
        "PHONETIC",
        "PIVOTBY",
        "POW",
        "PRICE",
        "PRICEDISC",
        "PRICEMAT",
        "PROB",
        "PROPER",
        "QUARTILE",
        "QUARTILE.EXC",
        "QUARTILE.INC",
        "QUERY",
        "RANDARRAY",
        "RANK",
        "RECEIVED",
        "REDUCE",
        "REGEXEXTRACT",
        "REGEXMATCH",
        "REGEXREPLACE",
        "REGISTER.ID",
        "REPLACE",
        "REPLACEB",
        "RIGHTB",
        "RTD",
        "SCAN",
        "SEARCHB",
        "SEQUENCE",
        "SERIESSUM",
        "SORT",
        "SORTBY",
        "SORTN",
        "SPARKLINE",
        "SPLIT",
        "STOCKHISTORY",
        "SUMPRODUCT",
        "TAKE",
        "TEXTSPLIT",
        "TOCOL",
        "TOROW",
        "TO_DATE",
        "TO_DOLLARS",
        "TO_PERCENT",
        "TO_PURE_NUMBER",
        "TO_TEXT",
        "TRANSPOSE",
        "TREND",
        "TRIMMEAN",
        "TRIMRANGE",
        "UMINUS",
        "UNARY_PERCENT",
        "UNICHAR",
        "UNIQUE",
        "UPLUS",
        "VDB",
        "VSTACK",
        "WEBSERVICE",
        "WRAPCOLS",
        "WRAPROWS",
        "XMATCH",
        "YIELD",
        "YIELDDISC",
        "YIELDMAT",
    ];

    for (idx, function) in functions.iter().enumerate() {
        let cell = format!("A{}", idx + 1);
        model._set(&cell, &format!("={function}(1)"));
    }
    model.evaluate();

    for row in 1..=functions.len() as i32 {
        let cell = format!("A{row}");
        assert_eq!(model._get_text(&cell), *"#N/IMPL!");
    }
}

#[test]
fn test_unknown_function_returns_name_error() {
    let mut model = new_empty_model();
    model._set("A1", "=NOT_A_FUNCTION(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#NAME?");
}

#[test]
fn test_batch_fallback_add() {
    let mut model = new_empty_model();
    model._set("A1", "=ADD(1,2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"6");
}

#[test]
fn test_batch_fallback_add_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ADD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"#ERROR!");
}

#[test]
fn test_batch_fallback_address() {
    let mut model = new_empty_model();
    model._set("A1", "=ADDRESS(2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"$C$2");
}

#[test]
fn test_batch_fallback_address_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ADDRESS(2,3,4)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"C2");
}

#[test]
fn test_batch_fallback_areas() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("B1", "=AREAS(A1:A2)");
    model.evaluate();

    assert_eq!(model._get_text("B1"), *"1");
}

#[test]
fn test_batch_fallback_arrayformula() {
    let mut model = new_empty_model();
    model._set("A1", "=ARRAYFORMULA(1+2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"3");
}

#[test]
fn test_batch_fallback_array_constrain() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(ARRAY_CONSTRAIN({1,2;3,4;5,6},2,1))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"4");
}

#[test]
fn test_batch_fallback_asc() {
    let mut model = new_empty_model();
    model._set("A1", "=ASC(\"ＡＢＣ\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"ABC");
}

#[test]
fn test_batch_fallback_average_weighted() {
    let mut model = new_empty_model();
    model._set("A1", "=AVERAGE.WEIGHTED({10,20,30},{1,2,3})");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"23.333333333");
}

#[test]
fn test_batch_fallback_beta_invn() {
    let mut model = new_empty_model();
    model._set("A1", "=BETA.INVN(0.5,2,2,0,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"0.5");
}

#[test]
fn test_batch_fallback_char() {
    let mut model = new_empty_model();
    model._set("A1", "=CHAR(65)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"A");
}

#[test]
fn test_batch_fallback_clean() {
    let mut model = new_empty_model();
    model._set("A1", "=CLEAN(\"A\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"A");
}

#[test]
fn test_batch_fallback_code() {
    let mut model = new_empty_model();
    model._set("A1", "=CODE(\"A\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"65");
}
