// AUTO-GENERATED by scripts/generate_batch_fallbacks.py
// Do not edit by hand.
#![allow(clippy::unwrap_used)]

use crate::test::util::new_empty_model;

#[test]
fn test_batch_unsupported_functions_return_nimpl() {
    let mut model = new_empty_model();
    let functions = [
        "IMPORTDATA",
        "IMPORTFEED",
        "IMPORTHTML",
        "IMPORTRANGE",
        "IMPORTXML",
        "IMTANH",
        "INTRATE",
        "ISBETWEEN",
        "ISDATE",
        "ISEMAIL",
        "ISOMITTED",
        "ISURL",
        "JIS",
        "JOIN",
        "LAMBDA",
        "LEFTB",
        "LENB",
        "LET",
        "LINEST",
        "LOGEST",
        "LT",
        "LTE",
        "MAKEARRAY",
        "MAP",
        "MARGINOFERROR",
        "MDETERM",
        "MDURATION",
        "MIDB",
        "MINUS",
        "MINVERSE",
        "MMULT",
        "MODE",
        "MODE.MULT",
        "MODE.SNGL",
        "MULTINOMIAL",
        "MULTIPLY",
        "MUNIT",
        "NE",
        "NUMBERVALUE",
        "ODDFPRICE",
        "ODDFYIELD",
        "ODDLPRICE",
        "ODDLYIELD",
        "PERCENTILE",
        "PERCENTILE.EXC",
        "PERCENTILE.INC",
        "PERCENTRANK",
        "PERCENTRANK.EXC",
        "PERCENTRANK.INC",
        "PERMUT",
        "PERMUTATIONA",
        "PHONETIC",
        "PIVOTBY",
        "POW",
        "PRICE",
        "PRICEDISC",
        "PRICEMAT",
        "PROB",
        "PROPER",
        "QUARTILE",
        "QUARTILE.EXC",
        "QUARTILE.INC",
        "QUERY",
        "RANDARRAY",
        "RANK",
        "RECEIVED",
        "REDUCE",
        "REGEXEXTRACT",
        "REGEXMATCH",
        "REGEXREPLACE",
        "REGISTER.ID",
        "REPLACE",
        "REPLACEB",
        "RIGHTB",
        "RTD",
        "SCAN",
        "SEARCHB",
        "SEQUENCE",
        "SERIESSUM",
        "SORT",
        "SORTBY",
        "SORTN",
        "SPARKLINE",
        "SPLIT",
        "STOCKHISTORY",
        "SUMPRODUCT",
        "TAKE",
        "TEXTSPLIT",
        "TOCOL",
        "TOROW",
        "TO_DATE",
        "TO_DOLLARS",
        "TO_PERCENT",
        "TO_PURE_NUMBER",
        "TO_TEXT",
        "TRANSPOSE",
        "TREND",
        "TRIMMEAN",
        "TRIMRANGE",
        "UMINUS",
        "UNARY_PERCENT",
        "UNICHAR",
        "UNIQUE",
        "UPLUS",
        "VDB",
        "VSTACK",
        "WEBSERVICE",
        "WRAPCOLS",
        "WRAPROWS",
        "XMATCH",
        "YIELD",
        "YIELDDISC",
        "YIELDMAT",
    ];

    for (idx, function) in functions.iter().enumerate() {
        let cell = format!("A{}", idx + 1);
        model._set(&cell, &format!("={function}(1)"));
    }
    model.evaluate();

    for row in 1..=functions.len() as i32 {
        let cell = format!("A{row}");
        assert_eq!(model._get_text(&cell), *"#N/IMPL!");
    }
}

#[test]
fn test_unknown_function_returns_name_error() {
    let mut model = new_empty_model();
    model._set("A1", "=NOT_A_FUNCTION(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#NAME?");
}

#[test]
fn test_batch_fallback_accrint() {
    let mut model = new_empty_model();
    model._set("A1", "=ACCRINT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_accrintm() {
    let mut model = new_empty_model();
    model._set("A1", "=ACCRINTM(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_add() {
    let mut model = new_empty_model();
    model._set("A1", "=ADD(1,2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"6");
}

#[test]
fn test_batch_fallback_add_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ADD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"#ERROR!");
}

#[test]
fn test_batch_fallback_address() {
    let mut model = new_empty_model();
    model._set("A1", "=ADDRESS(2,3)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"$C$2");
}

#[test]
fn test_batch_fallback_address_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=ADDRESS(2,3,4)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"C2");
}

#[test]
fn test_batch_fallback_aggregate() {
    let mut model = new_empty_model();
    model._set("A1", "=AGGREGATE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_amordegrc() {
    let mut model = new_empty_model();
    model._set("A1", "=AMORDEGRC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_amorlinc() {
    let mut model = new_empty_model();
    model._set("A1", "=AMORLINC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_areas() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("B1", "=AREAS(A1:A2)");
    model.evaluate();

    assert_eq!(model._get_text("B1"), *"1");
}

#[test]
fn test_batch_fallback_arrayformula() {
    let mut model = new_empty_model();
    model._set("A1", "=ARRAYFORMULA(1+2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"3");
}

#[test]
fn test_batch_fallback_array_constrain() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(ARRAY_CONSTRAIN({1,2;3,4;5,6},2,1))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"4");
}

#[test]
fn test_batch_fallback_asc() {
    let mut model = new_empty_model();
    model._set("A1", "=ASC(\"ＡＢＣ\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"ABC");
}

#[test]
fn test_batch_fallback_average_weighted() {
    let mut model = new_empty_model();
    model._set("A1", "=AVERAGE.WEIGHTED({10,20,30},{1,2,3})");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"23.333333333");
}

#[test]
fn test_batch_fallback_bahttext() {
    let mut model = new_empty_model();
    model._set("A1", "=BAHTTEXT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_beta_invn() {
    let mut model = new_empty_model();
    model._set("A1", "=BETA.INVN(0.5,2,2,0,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"0.5");
}

#[test]
fn test_batch_fallback_bycol() {
    let mut model = new_empty_model();
    model._set("A1", "=BYCOL(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_byrow() {
    let mut model = new_empty_model();
    model._set("A1", "=BYROW(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_call() {
    let mut model = new_empty_model();
    model._set("A1", "=CALL(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_char() {
    let mut model = new_empty_model();
    model._set("A1", "=CHAR(65)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"A");
}

#[test]
fn test_batch_fallback_choosecols() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(CHOOSECOLS({1,2;3,4},2))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"6");
}

#[test]
fn test_batch_fallback_choosecols_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(CHOOSECOLS({1,2,3;4,5,6},-1))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"9");
}

#[test]
fn test_batch_fallback_chooserows() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(CHOOSEROWS({1,2;3,4},2))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"7");
}

#[test]
fn test_batch_fallback_chooserows_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(CHOOSEROWS({1,2;3,4},-1))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"7");
}

#[test]
fn test_batch_fallback_clean() {
    let mut model = new_empty_model();
    model._set("A1", "=CLEAN(\"A\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"A");
}

#[test]
fn test_batch_fallback_code() {
    let mut model = new_empty_model();
    model._set("A1", "=CODE(\"A\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"65");
}

#[test]
fn test_batch_fallback_copilot() {
    let mut model = new_empty_model();
    model._set("A1", "=COPILOT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_countunique() {
    let mut model = new_empty_model();
    model._set("A1", "1");
    model._set("A2", "2");
    model._set("A3", "2");
    model._set("A4", "3");
    model._set("B1", "=COUNTUNIQUE(A1:A4)");
    model.evaluate();

    assert_eq!(model._get_text("B1"), *"3");
}

#[test]
fn test_batch_fallback_coupdaybs() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPDAYBS(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupdays() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPDAYS(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupdaysnc() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPDAYSNC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupncd() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPNCD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_coupnum() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPNUM(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_couppcd() {
    let mut model = new_empty_model();
    model._set("A1", "=COUPPCD(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_critbinom() {
    let mut model = new_empty_model();
    model._set("A1", "=CRITBINOM(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubekpimember() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEKPIMEMBER(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubemember() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEMEMBER(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubememberproperty() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEMEMBERPROPERTY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cuberankedmember() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBERANKEDMEMBER(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubeset() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBESET(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubesetcount() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBESETCOUNT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_cubevalue() {
    let mut model = new_empty_model();
    model._set("A1", "=CUBEVALUE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_dbcs() {
    let mut model = new_empty_model();
    model._set("A1", "=DBCS(\"ABC\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"ＡＢＣ");
}

#[test]
fn test_batch_fallback_detectlanguage() {
    let mut model = new_empty_model();
    model._set("A1", "=DETECTLANGUAGE(\"Hello\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"en");
}

#[test]
fn test_batch_fallback_disc() {
    let mut model = new_empty_model();
    model._set("A1", "=DISC(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_divide() {
    let mut model = new_empty_model();
    model._set("A1", "=DIVIDE(10,2)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"5");
}

#[test]
fn test_batch_fallback_divide_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=DIVIDE(1,0)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"#DIV/0!");
}

#[test]
fn test_batch_fallback_dollar() {
    let mut model = new_empty_model();
    model._set("A1", "=DOLLAR(1234.5)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"$1,234.50");
}

#[test]
fn test_batch_fallback_dollar_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=DOLLAR(1.236,1)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"$1.2");
}

#[test]
fn test_batch_fallback_drop() {
    let mut model = new_empty_model();
    model._set("A1", "=SUM(DROP({1,2;3,4},1,1))");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"4");
}

#[test]
fn test_batch_fallback_drop_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=SUM(DROP({1,2;3,4},-1,-1))");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"1");
}

#[test]
fn test_batch_fallback_duration() {
    let mut model = new_empty_model();
    model._set("A1", "=DURATION(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_encodeurl() {
    let mut model = new_empty_model();
    model._set("A1", "=ENCODEURL(\"https://example.com/hello world\")");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"https%3A%2F%2Fexample.com%2Fhello%20world");
}

#[test]
fn test_batch_fallback_epochtodate() {
    let mut model = new_empty_model();
    model._set("A1", "=EPOCHTODATE(0)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"25569");
}

#[test]
fn test_batch_fallback_epochtodate_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=EPOCHTODATE(86400)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"25570");
}

#[test]
fn test_batch_fallback_eq() {
    let mut model = new_empty_model();
    model._set("A1", "=EQ(1,1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"TRUE");
}

#[test]
fn test_batch_fallback_eq_extra() {
    let mut model = new_empty_model();
    model._set("A2", "=EQ(1,2)");
    model.evaluate();

    assert_eq!(model._get_text("A2"), *"FALSE");
}

#[test]
fn test_batch_fallback_euroconvert() {
    let mut model = new_empty_model();
    model._set("A1", "=EUROCONVERT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_expand() {
    let mut model = new_empty_model();
    model._set("A1", "=EXPAND(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_filter() {
    let mut model = new_empty_model();
    model._set("A1", "=FILTER(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_filterxml() {
    let mut model = new_empty_model();
    model._set("A1", "=FILTERXML(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_findb() {
    let mut model = new_empty_model();
    model._set("A1", "=FINDB(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_fixed() {
    let mut model = new_empty_model();
    model._set("A1", "=FIXED(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_flatten() {
    let mut model = new_empty_model();
    model._set("A1", "=FLATTEN(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_ets() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_ets_confint() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS.CONFINT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_ets_seasonality() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS.SEASONALITY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_ets_stat() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.ETS.STAT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_forecast_linear() {
    let mut model = new_empty_model();
    model._set("A1", "=FORECAST.LINEAR(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_frequency() {
    let mut model = new_empty_model();
    model._set("A1", "=FREQUENCY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_fvschedule() {
    let mut model = new_empty_model();
    model._set("A1", "=FVSCHEDULE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_getpivotdata() {
    let mut model = new_empty_model();
    model._set("A1", "=GETPIVOTDATA(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_googlefinance() {
    let mut model = new_empty_model();
    model._set("A1", "=GOOGLEFINANCE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_googletranslate() {
    let mut model = new_empty_model();
    model._set("A1", "=GOOGLETRANSLATE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_groupby() {
    let mut model = new_empty_model();
    model._set("A1", "=GROUPBY(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_growth() {
    let mut model = new_empty_model();
    model._set("A1", "=GROWTH(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_gt() {
    let mut model = new_empty_model();
    model._set("A1", "=GT(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_gte() {
    let mut model = new_empty_model();
    model._set("A1", "=GTE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_hstack() {
    let mut model = new_empty_model();
    model._set("A1", "=HSTACK(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_hyperlink() {
    let mut model = new_empty_model();
    model._set("A1", "=HYPERLINK(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_image() {
    let mut model = new_empty_model();
    model._set("A1", "=IMAGE(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_imcoth() {
    let mut model = new_empty_model();
    model._set("A1", "=IMCOTH(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}

#[test]
fn test_batch_fallback_imlog() {
    let mut model = new_empty_model();
    model._set("A1", "=IMLOG(1)");
    model.evaluate();

    assert_eq!(model._get_text("A1"), *"#N/IMPL!");
}
